openshift/console-operator

deploy/operator.yaml
hack/build.sh
hack/clean.sh
hack/test-e2e.sh
hack/test-integration.sh
hack/test-unit.sh
hack/test.sh

Improving my tests scripts w/some cleanup, etc 
@spadgett @jwforres  
@rhamilto @sg00dwin  
@enj @juanvallejo  
just need an lgtm from anyone who is out there on the internets listening 😄

Update /hack scripts with various lib functions

---

OWNERS

Adjust OWNERS for console-operator

---

Dockerfile

Cleanup & updating to match some other root Dockerfiles

Revise root Dockerfile

---

pkg/operator/configmap.go
pkg/operator/deployment.go
pkg/operator/route.go
pkg/operator/service.go

Tiny change just to improve log output

Add name to log statements

---

.gitignore
examples/cr.yaml
manifests/00-oauth.yaml
pkg/operator/configmap.go
pkg/operator/deployment.go
pkg/operator/oauth.go
pkg/operator/reconcile.go
pkg/operator/route.go
pkg/operator/service.go
pkg/stub/handler.go

Update oauth client to be created via /manifests, but updated via operator

---

examples/cr.yaml
pkg/apis/console/v1alpha1/types.go
pkg/operator/configmap.go
pkg/operator/console.go
pkg/operator/deployment.go
pkg/operator/oauth.go
pkg/operator/reconcile.go
pkg/operator/route.go
pkg/operator/service.go
pkg/operator/util.go
pkg/stub/handler.go

Add ManagementState to handle paused, unpaused, deleted  as managed, unmanaaged, removed.

Add ManagementState to handle paused, unpaused, deleted

---

README.md

@spadgett @enj 
Time to catch this up again.

Update README.md to reflect current dev practices

---

pkg/operator/deployment.go
pkg/operator/reconcile.go

Add annotation to PodSpec on Deployment whenever ConfigMap changes ResourceVersion changes to ensure Pod is redeployed

Add annotation to PodSpec on Deployment whenever ConfigMap changes

---

README.md

Update README to latest instructions for building, deploying and running the console-operator.

Update README to latest instructions 

---

README.md

Add block to README for local dev with correct operator service account token

Add block to README for local dev with correct operator token

---

manifests/05-operator.yaml
pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/oauthclient/oauthclient.go
pkg/console/subresource/secret/secret.go
pkg/controller/api.go

- Cleans up the `sync_v400` fn
- breaks this function down into multiple smaller functions
- Fixes issue where `oauthclient` `redirectURI` might not be set correctly
/assign @enj

Sync loop update

---

pkg/console/operator/sync_v400.go
pkg/console/subresource/deployment/deployment.go

Updates the `SyncDeployment()` fn to take the `secret` and `configmap`, and test the resource versions against what is recorded on the pod template.  this will be used to force a pod rollout instead of a boolean and should be more reliable (for example, if one of the dependencies changed on a previous sync, but the sync died). 
@enj @spadgett

Update Deployment sync to check configmap and secret resource versions

---

examples/cr.yaml
pkg/console/operator/operator.go

Fixes issue #83 
@jwforres @spadgett

Ensure minimum 2 replicas of console

---

manifests/05-operator.yaml

Per discussion, the operator should have more than 1 replica.  Updating to 3.

Update operator replicas to 3

---

manifests/05-operator.yaml
pkg/console/subresource/deployment/deployment.go

/assign @jhadvig @benjaminapetersen

Set a 10m CPU request for console operator and console

---

examples/cr.yaml
manifests/05-operator.yaml
pkg/console/operator/operator.go

Per discussion in slack @spadgett

Reduce Operator & Console replicas to 2 each

---

pkg/boilerplate/controller/controller.go
pkg/boilerplate/controller/die.go
pkg/boilerplate/controller/filter.go
pkg/boilerplate/controller/informer.go
pkg/boilerplate/controller/option.go
pkg/boilerplate/controller/sync.go
pkg/boilerplate/operator/option.go
pkg/boilerplate/operator/sync.go

Bumping boilerplate for better logging, etc.

bump: boilerplate

---

pkg/console/operator/sync_v400.go

/assign @benjaminapetersen @enj

Public hostname should be the hostname, not URL

---

pkg/console/starter/starter.go

Protobuf!  
https://jira.coreos.com/browse/CONSOLE-1046
/assign @enj 
@spadgett fyi

Use proto kubeconfig instead of kubeconfig

---

pkg/console/starter/starter.go

There is no reason to watch any other route.

Filter route watch to only "console"

---

pkg/console/subresource/deployment/deployment.go

/assign @enj @benjaminapetersen

Increase initial delay of console liveness probe

---

pkg/console/subresource/oauthclient/oauthclient.go
pkg/console/subresource/oauthclient/oauthclient_test.go

Restrict console OAuthClient redirect to `/auth/callback` path

---

manifests/03-rbac-role.yaml
pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/starter/starter.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go

bug 1664574
([link](https://bugzilla.redhat.com/show_bug.cgi?id=1664574))
- Add `infrastructureConfig` to supply console `configmap` with `masterPublicURL`.
This will likely conflict with #162

Fix missing masterPublicURL on console configmap

---

manifests/05-version-mapping.yaml
manifests/07-operator.yaml
manifests/08-clusteroperator.yaml
pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/starter/starter.go
pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/deployment/deployment_test.go

First work based on discussion with @benjaminapetersen and @enj 
Please take a look and let me know whats missing besides the watching the CM (and if we actually need it...)
Thanks

Report Operand version

---

pkg/console/operator/sync_v400.go

Bug 1689773: Set proper status when console route is not admitted

---

pkg/console/operator/sync_v400.go

Remove duplicate import

---

pkg/console/operator/sync_v400.go

Remove unused sync funcs

---

pkg/console/operator/sync_v400.go

Fix Sprintf "deployment" for SyncDeployment() error

---

pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/deployment/deployment_test.go

Comments in code
Story: https://jira.coreos.com/browse/CONSOLE-1320

Handle Console Operator LogLevel

---

pkg/console/starter/starter.go
pkg/console/subresource/configmap/configmap_test.go

Use const in configmap test, eliminate stale comments

---

pkg/console/starter/starter.go

Imports are messy, just need a little cleanup.

Fix imports in starter.go

---

pkg/console/operator/sync_v400.go

It is incorrect to `error` when we create our secret on a 404.  This is blocking, so it is fine to immediately go from `not found` to `create` and after that return errors.

Simplify SyncSecret()

---

pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/deployment/deployment.go

Lowering capital letter for logrus and fmt messages

---

pkg/console/operator/operator.go

Fix typo completele/complete

---

pkg/console/subresource/configmap/brand_ocp.go
pkg/console/subresource/configmap/brand_okd.go
pkg/console/subresource/configmap/configmap_test.go

/assign @zherman0 
/cc @benjaminapetersen

Switch doc links to version 4.1

---

pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go

Change the auto generated default api version to use the correct v1 instead of v1beta1

Change default api value to v1

---

pkg/console/subresource/deployment/deployment.go

pkg/console/subresource/deployment: Fix "avalable" -> "available" typo

---

manifests/01-oauth.yaml

/assign @enj @benjaminapetersen

Add `release.openshift.io/create-only` annotation to OAuthClient

---

manifests/05-version-mapping.yaml

/assign @enj @benjaminapetersen

Remove version-mapping config map

---

pkg/console/errors/sync_errors.go
pkg/console/operator/operator.go
pkg/console/operator/status.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/deployment/deployment_test.go
pkg/console/subresource/oauthclient/oauthclient.go
pkg/console/subresource/route/route.go
pkg/testframework/framework.go
test/e2e/managed_test.go
test/e2e/removed_test.go
test/e2e/unmanaged_test.go

- Removes log spam & adds specificity when logging happens to help ensure all logs are meaningful
- Ensures Status Available settings are accurate and reduces the possibility of status flutter.

Improve Status:Available & improve logging

---

pkg/console/subresource/deployment/deployment.go
pkg/testframework/console-operator.go
pkg/testframework/framework.go
test/e2e/logging_test.go
test/e2e/managed_test.go
test/e2e/removed_test.go
test/e2e/unmanaged_test.go

Check the tests comments
Story: https://jira.coreos.com/browse/CONSOLE-1354

e2e tests for LogLevel

---

pkg/testframework/framework.go

Just a small fix that was missed by last review

Remove noisy print

---

test/e2e/logging_test.go
test/e2e/managed_test.go
test/e2e/unmanaged_test.go

e2e tests setup refactoring

---

manifests/07-downloads-deployment.yaml

in service to https://github.com/openshift/origin/pull/22787

manifests: add resource requests to downloads pod

---

manifests/00-crd-operator-config.yaml
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go
test/e2e/providers_test.go

Add providers with statuspage.io to operator config

---

pkg/console/operator/operator.go
pkg/console/operator/status.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/route/route.go
pkg/console/subresource/util/util.go

Replaces `logrus` with `klog`.  
Fixes https://jira.coreos.com/browse/CONSOLE-1332
Fixes https://jira.coreos.com/browse/CONSOLE-1177

Replace logrus with klog

---

examples/07-operator-alt-image.yaml

/assign @jhadvig @zherman0 
Trivial example update since we dropped that flag.

Update example operator yaml with alt image

---

pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go

Promotes the `sync()` funcs to Methods on the Operator from standalone funcs.  

Promote sync() funcs to methods on the operator

---

manifests/07-downloads-deployment.yaml

https://jira.coreos.com/browse/CONSOLE-1565

Add `nodeSelector` to downloads deployment

---

manifests/00-crd-extension-console-link.yaml

Following these changes: https://github.com/openshift/api/pull/360
@spadgett @jhadvig @rhamilto

Add applicationMenu to ConsoleLink CRD

---

pkg/console/subresource/deployment/deployment.go

Thought that we are setting the flags from the console-config. Instead we have to set them directly from the operator.

Set statuspage-id flag

---

test/e2e/providers_test.go

Add e2e test to test if --statuspage-id flag was set on console's pod template

---

pkg/console/subresource/configmap/brand_ocp.go
pkg/console/subresource/configmap/brand_okd.go
pkg/console/subresource/configmap/configmap_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1739312
/cc @zherman0 @benjaminapetersen

Bug 1739312: Update doc URL to 4.2

---

pkg/console/operator/operator.go
pkg/console/operator/status.go
pkg/console/operator/sync_v400.go
pkg/console/starter/starter.go
test/e2e/framework/console-operator.go

Implements part of #260 
Degraded is a pretty significant status in terms of our telemetry, but also infrequently used in code.  Updating first for these reasons.
@spadgett

Add condition handlers, implement for Degraded prefixing, add StaleConditionController

---

pkg/console/operator/status.go
pkg/console/operator/sync_v400.go
pkg/console/starter/starter.go
test/e2e/framework/console-operator.go

Depends on #269 & will be rebased once it is merged.
Re [bugzilla 1740387](https://bugzilla.redhat.com/show_bug.cgi?id=1740387) - partial fix.
@spadgett fyi this would update many of the ambiguous conditions we are seeing.

Update Progressing condition to use handler

---

pkg/console/operator/status.go

Handle error by proper status condition

---

pkg/console/operator/sync_v400.go

Make sure configMap with custom logo is created before mount

---

pkg/console/operator/sync_v400.go

Reverts openshift/console-operator#289
@spadgett FYI

Bug 1750790: Revert "Make sure configMap with custom logo is created before mount"

---

test/e2e/brand_customization_test.go

Fix custom-logo e2e test

---

test/e2e/brand_customization_test.go

We needed to update the `TestCustomBrand`, to cover all the different use-cases that had caused issues recently and have been fixed.
Updated test covers following cases, in given order:
- image with binary representation (.png) is set as a custom-logo
- custom-logo gets changed
- product-name gets changed
- image with string representation (.svg) is set as a custom-logo
- custom-logo gets unset

Update TestCustomBrand e2e test

---

pkg/console/operator/operator.go

Remove unused argument

---

manifests/00-crd-extension-console-cli-download.yaml
manifests/00-crd-extension-console-link.yaml
manifests/00-crd-extension-console-notification.yaml

Updated just the validation pattern since if I've would copied the CRD yamls from openshift/api master, there would be more changes then necessary.
cc'ing @spadgett

Bug 1764227: Incorrect validation pattern on ConsoleCLIDownloads Href field

---

test/e2e/removed_test.go
test/e2e/unmanaged_test.go

Skip Unmanaged and Removed TCs

---

glide.lock
vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go

Bug 1768542: Bump deps

---

test/e2e/brand_builtins_test.go
test/e2e/framework/console-operator.go

Replacing logging provided by the `fmt` package, with the logging from the `testing` package, for consistency.

Refactor logging

---

pkg/console/operator/sync_v400.go

openshift resources in the kube block of imports.

Cleanup disorganized imports in sync_v400.go

---

pkg/console/subresource/configmap/brand_ocp.go
pkg/console/subresource/configmap/brand_okd.go
pkg/console/subresource/configmap/configmap_test.go

Bug 1773431: Update doc link for 4.3

---

manifests/03-rbac-role-ns-openshift-config-managed.yaml

/assign @benjaminapetersen @jhadvig

manifests: allow console service account to list managed configmaps

---

manifests/03-rbac-role-cluster-extensions.yaml

/assign @benjaminapetersen @jhadvig

Bug 1783163: fix RBAC for ConsoleYAMLSample

---

pkg/api/api.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go
pkg/console/subresource/consoleserver/config_builder.go
pkg/console/subresource/consoleserver/config_builder_test.go
pkg/console/subresource/consoleserver/types.go

Bug 1777486: Update the monitoring and logging URLs name

---

pkg/api/api.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go
pkg/console/subresource/consoleserver/config_builder.go
pkg/console/subresource/consoleserver/config_builder_test.go
pkg/console/subresource/consoleserver/types.go

Manual cherrypick of:
- https://github.com/openshift/console-operator/pull/381
- https://github.com/openshift/console-operator/pull/383
since they are aiming for the same fix.

 [release-4.4] Bug 1804884: Add monitoring-shared-config configmaps from openshift-config-managed to the console-config

---

pkg/console/subresource/configmap/brand_ocp.go
pkg/console/subresource/configmap/brand_okd.go

Story: https://issues.redhat.com/browse/CONSOLE-2019

Bump DEFAULT_DOC_URL for okd & ocp

---

pkg/console/controllers/clidownloads/controller.go

Sync operands status in clidownloads controller

---

pkg/console/operator/sync_v400.go

Remove duplicit imports

---

Makefile

Add 'make test-unit' to autocomplete

---

OWNERS

Update OWNERS file with component

---

pkg/console/controllers/route/controller.go

Bug 1826628: Delete custom route after it is unset from console operator config

---

pkg/console/subresource/deployment/deployment.go

Bug 1826046: declare correct container port in console pod spec

---

pkg/api/api.go
pkg/console/controllers/route/controller.go
pkg/console/controllers/service/controller.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go
pkg/console/subresource/consoleserver/config_builder.go
pkg/console/subresource/consoleserver/config_builder_test.go
pkg/console/subresource/consoleserver/types.go
pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/deployment/deployment_test.go
pkg/console/subresource/route/route.go
pkg/console/subresource/route/route_test.go
pkg/console/subresource/service/service.go
pkg/console/subresource/service/service_test.go

Bug 1826873: Default console route should redirect to correct public URL when route hostname has been customized

---

test/e2e/custom_url_test.go

Bug 1829236: CustomURL e2e

---

OWNERS

Since Ben moving 😢  
@spadgett FYI

Add approver

---

pkg/console/operator/sync_v400.go

Before we forget...
Do we wanna backport to 4.5 ? If so I guess we need 4.6 & 4.5 BZ, right ?

Check and flush proper error

---

Dockerfile.rhel7

We need to change the maintainer as well and since Im the second biggest contributor it should be most probably me.

Change maintainer

---

vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
vendor/github.com/openshift/api/config/v1/types_oauth.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

Update go mod vendors

---

pkg/console/subresource/configmap/brand_ocp.go
pkg/console/subresource/configmap/brand_okd.go

Bug 1856667: Bump DEFAULT_DOC_URL for okd & ocp

---

manifests/0000_90_console-operator_01_prometheusrbac.yaml
manifests/0000_90_console-operator_02_servicemonitor.yaml
manifests/01-helm.yaml
manifests/01-oauth.yaml
manifests/01-operator-config.yaml
manifests/02-namespace.yaml
manifests/03-rbac-role-cluster-extensions.yaml
manifests/03-rbac-role-cluster.yaml
manifests/03-rbac-role-ns-console.yaml
manifests/03-rbac-role-ns-openshift-config-managed.yaml
manifests/03-rbac-role-ns-openshift-config.yaml
manifests/03-rbac-role-ns-operator.yaml
manifests/04-rbac-rolebinding-cluster.yaml
manifests/04-rbac-rolebinding.yaml
manifests/05-config-public.yaml
manifests/05-config.yaml
manifests/05-service.yaml
manifests/06-sa.yaml
manifests/07-downloads-deployment.yaml
manifests/07-downloads-helm.yaml
manifests/07-downloads-route.yaml
manifests/07-downloads-service.yaml
manifests/07-operator.yaml
manifests/08-clusteroperator.yaml
manifests/09-console-link-openshift-blog.yaml
manifests/09-console-link-openshift-learning-portal.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

manifests/02-namespace.yaml
manifests/03-rbac-role-ns-openshift-console-user-settings.yaml

Adds ROKS profile annotation to recently added manifests (#479)

Add ROKS profile annotation to recently added manifests

---

quickstarts/explore-serverless-quickstart.yaml

Updating Serverless Quick Start at the request of @beaumorley.
/assign @jhadvig @spadgett

Update Serverless Quick Start

---

test/e2e/custom_url_test.go
test/e2e/plugins_test.go
test/e2e/providers_test.go

Fixing occasional flakes, since inside the `RetryOnConflict` loop we should be fetching latest version of the console-operator config.

RetryOnConflict should be fetching latest version of console-operator config

---

pkg/console/subresource/configmap/brand_ocp.go

@jhadvig  Can you please help review?

Bug 1937627: Bump DEFAULT_DOC_URL for 4.8

---

pkg/console/controllers/clidownloads/controller.go
pkg/console/controllers/downloadsdeployment/controller.go
pkg/console/controllers/route/controller.go
pkg/console/controllers/service/controller.go
pkg/console/operator/operator.go

We should be periodically resyncing each controller.

Bug 1945326: Resync controllers every minute

---

pkg/console/controllers/downloadsdeployment/controller.go
pkg/console/starter/starter.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go

Bug 1957198: Remove misspelled console-operator condition

---

pkg/console/controllers/route/controller.go

If the console-operator config is being configured with custom domain for the `console` route, warn user that this type of configuration is deprecated and navigate him where the configuration should be moved and how does it should look like.
cc'ing @TheRealJon @florkbr

Bug 1959696: Add warning log message when custom domain is configured on console-operator config

---

quickstarts/add-healthchecks-quickstart.yaml
quickstarts/monitor-sampleapp-quickstart.yaml
quickstarts/node-with-s2i.yaml
quickstarts/quarkus-with-s2i.yaml
quickstarts/sample-application-quickstart.yaml
quickstarts/spring-with-s2i.yaml

This fixes https://bugzilla.redhat.com/show_bug.cgi?id=2000768
**Fixed Issues** 
1. There are 4 Quick Starts which show the user how to View the associated code via the code decorator in the Topology view.  The current QS indicate that the code decorator always bring you to the associated git repository.
_Resolution_: The content now explains that the code decorator will either bring you to the associated git repo or to your IDE if Eclipse Che or CRW Operators are installed.
1. The deployment name was incorrect ( due to the fact that theses QS were initially copies of one another)
_Resolution_: Incorrect deployment names were updated.
1. The deployment name from the Node.js sample was renamed when moving from s2i samples to devfile samples, but the quick starts weren't updated …

Bug 2000768: Fix 4 Quick Starts

---

pkg/console/subresource/deployment/deployment.go
pkg/console/subresource/deployment/deployment_test.go

Manual backport of:
- https://github.com/openshift/console-operator/pull/560
- https://github.com/openshift/console-operator/pull/566

[release-4.8] Bug 2003639: Use kubernetes.io/hostname for workload anti-affi… …nity

---

manifests/03-rbac-role-cluster.yaml

This PR is in conjunction with: https://github.com/openshift/console/pull/10045
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

Bug 2009454: Change web terminal subscription permissions from get to list

---

quickstarts/install-odf.yaml

FollowUp PR for https://github.com/openshift/console-operator/pull/598 based on https://bugzilla.redhat.com/show_bug.cgi?id=2013632#c4

Bug 2013632: Correct grammar error in ODF quickstart

---

pkg/console/subresource/configmap/brand_ocp.go

Bug 2021400: Bump documentationBaseURL to 4.10

---

bindata/services/console-redirect-service.yaml
bindata/services/console-service.yaml
manifests/05-service.yaml
pkg/console/assets/bindata.go
pkg/console/subresource/configmap/service_ca.go
test/e2e/util.go

Bug 2030574: Console resources are using older 'service.alpha.openshift.io' annotation

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/modules.txt

[release-4.9] Bug 2040275: Bump build-machinery-go for console-operator to pickup change in yaml-patch repository

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/modules.txt

[release-4.8] Bug 2041359: Bump build-machinery-go for console-operator to pickup change in yaml-patch repository

---

OWNERS

Add Jon Jackson to approvers list

---

pkg/console/controllers/route/controller.go
pkg/console/subresource/route/route.go
test/e2e/custom_url_test.go

Manual cheery-pick of https://github.com/openshift/console-operator/pull/624/commits/9c5b4f7d720946a05be823f950bd8546bc0fd212

[release-4.8] Bug 2071200: Fix setting of custom cert for default route

---

test/e2e/metrics_test.go

Backporting both https://github.com/openshift/console-operator/pull/640 && https://github.com/openshift/console-operator/pull/645

[release-4.10] Bug 2059992: Re-enable TestMetricsEndpoint e2e test case

---

pkg/console/subresource/configmap/brand_ocp.go

Bug 2075478: Bump docs version to 4.11

---

pkg/console/controllers/route/controller.go
pkg/console/subresource/route/route.go
test/e2e/util.go

Bug 2117646: Changing  field on any of routes in the openshift-console namespace wont trigger sync loop

---

test/e2e/removed_test.go
test/e2e/util.go

OCPBUGS-457: TestEditUnmanagedPodDisruptionBudget flakes

---

pkg/cmd/crdconversionwebhook/converter/converter.go
pkg/cmd/crdconversionwebhook/converter/converter_test.go

OCPBUGS-1708: Set i18n LoadType to Lazy when v1alpha1 i18n annotation is set to false

---

bindata/deployments/console-deployment.yaml
bindata/deployments/downloads-deployment.yaml
pkg/console/assets/bindata.go
pkg/console/subresource/deployment/deployment_test.go

/assign @TheRealJon 
@wking could you please help review this PR, if any other changes are necessary? 
Thanks

OCPBUGS-1617: Remove unused node.kubernetes.io/not-reachable toleration

---

quickstarts/host-inventory-quickstart.yaml

Signed-off-by: Maggie Chen <magchen@redhat.com>
https://issues.redhat.com/browse/ACM-2360

ACM-2360: Add more steps to host inventory quick start

---

quickstarts/install-multicluster-engine.yaml

PD-1365: Add quickstart - Get started with multicluster engine

---

test/e2e/unmanaged_test.go

OCPBUGS-6520: Test if all tested resrouces are available before launching Unmanaged* e2e tests

---

pkg/console/controllers/upgradenotification/controller.go

OCPBUGS-6488: Recover ConsoleNotificationSync after being degraded

---

quickstarts/host-inventory-quickstart.yaml
quickstarts/install-multicluster-engine.yaml

https://issues.redhat.com/browse/OCPBUGS-5893

OCPBUGS-5893: Back port on-premise host inventory quick start to OCP 4.10

---

.ci-operator.yaml
Dockerfile.rhel7
go.mod
pkg/console/assets/bindata.go

Superseds https://github.com/openshift/console-operator/pull/737

OCPBUGS-10108: ART image update

---

pkg/console/controllers/route/controller.go
pkg/console/subresource/route/route.go
test/e2e/util.go

Manual backport of https://github.com/openshift/console-operator/pull/672

OCPBUGS-11969: Changing  field on any of routes in the openshift-console namespace wont trigger sync loop

---

quickstarts/jboss-eap7-with-helm.yaml

It showcases how to build and deploy a JBoss EAP 7 application using Helm.

ODC-7312: Add OpenShift Quickstart for JBoss EAP 7

---

quickstarts/consolequickstart-install-cryostat.yaml

New quickstart for installing Cryostat. This was created by the Cryostat team, and reviewed by their docs team. This addresses on of the 4.14 epic - https://issues.redhat.com/browse/ODC-7111

ODC-7292: Add new quickstart for installing Cryostat

---

quickstarts/consolequickstart-install-cryostat.yaml

Updated Cryostat quick start for PR comment - https://github.com/openshift/console-operator/pull/770#pullrequestreview-1501727662

ODC-7339: Follow up ticket for ODC-7292

---

go.mod
go.sum
pkg/console/operator/operator.go
pkg/console/status/status.go
vendor/modules.txt

OCPBUGS-19080: Reset console operator's conditions

---

pkg/api/api.go
pkg/console/controllers/clidownloads/controller.go
pkg/console/starter/starter.go

[release-4.13] OCPBUGS-18972: Manual backport of #761

---

quickstarts/janus-idp-installation-via-helm.yaml
quickstarts/janus-idp-installation-via-operator.yaml
quickstarts/rhdh-installation-via-helm.yaml
quickstarts/rhdh-installation-via-operator.yaml

**Implements:**
https://issues.redhat.com/browse/ODC-7418
This PR adds four new Quick Starts:
1. Install Janus IDP with a Helm Chart ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-helm.yaml))
2. Install Janus IDP with an Operator ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-operator.yaml))
3. Install Red Hat Developer Hub (RHDH) with a Helm Chart ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/rhdh-installation-via-helm.yaml))
4. Install Red Hat Developer Hub (RHDH) with an Operator ([QuickStart YAML on …

ODC-7418: Add Janus IDP and RHDH Quick starts

---

pkg/console/subresource/configmap/brand_ocp.go

OCPBUGS-22681: Bump documentationBaseURL to 4.15

---

pkg/console/controllers/oauthclients/oauthclients.go

OCPBUGS-28982: oauthclients: fix oauthclients degraded condition that never gets removed

---

pkg/console/controllers/oauthclients/oauthclients.go
pkg/console/starter/starter.go

manual backport of #855 , cherry picked on top of #854 to avoid merge conflicts

[release-4.15] OCPBUGS-29010: oauthclients: fix oauthclients degraded condition that never gets removed

---

pkg/console/controllers/oauthclientsecret/oauthclientsecret.go
pkg/console/controllers/oidcsetup/oidcsetup.go
pkg/console/starter/starter.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/configmap/configmap_test.go
pkg/console/subresource/configmap/service_ca_test.go
pkg/console/subresource/consoleserver/config_builder.go
pkg/console/subresource/consoleserver/config_builder_test.go
pkg/console/subresource/deployment/deployment_test.go
pkg/console/subresource/secret/secret_test.go
pkg/console/subresource/util/util.go
pkg/console/subresource/util/util_test.go

OCPBUGS-31482: oidc: synchronize the CM with a CA to trust the issuer, if configured

---

quickstarts/impersonate-user.yaml

CONSOLE-3910: Add quickstart to impersonate a system:admin user

---

manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/console/controllers/oidcsetup/oidcsetup.go
pkg/console/operator/sync_v400.go
pkg/console/starter/starter.go
pkg/console/subresource/configmap/configmap_test.go
pkg/console/subresource/consoleserver/config_builder.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
vendor/modules.txt

/assign @deads2k 
/cc @jhadvig

OCPBUGS-32400: base OIDC status updates on the ExternalOIDC feature gate

---

pkg/api/api.go
pkg/console/controllers/clioidcclientstatus/controller.go
pkg/console/controllers/oauthclientsecret/oauthclientsecret.go
pkg/console/controllers/oidcsetup/oidcsetup.go
pkg/console/controllers/util/util.go
pkg/console/operator/operator.go
pkg/console/starter/starter.go
pkg/console/subresource/authentication/cluster.go
pkg/console/subresource/authentication/cluster_test.go
pkg/console/subresource/configmap/configmap.go
pkg/console/subresource/consoleserver/config_builder.go
pkg/console/subresource/consoleserver/config_builder_test.go
pkg/console/subresource/consoleserver/types.go
pkg/console/subresource/crd/authentications.go
pkg/console/subresource/infrastructure/cluster.go
pkg/console/subresource/util/util.go

Add external OIDC CLI login command to console config

CONSOLE-3902: Add cli login commands to console configmap

---

pkg/console/operator/operator.go
pkg/console/status/status.go

Manual cherry-pick of https://github.com/openshift/console-operator/pull/796

[release-4.13] OCPBUGS-18674: Reset console operator's conditions

---

pkg/console/controllers/clidownloads/controller.go
pkg/console/controllers/healthcheck/controller.go
pkg/console/controllers/route/controller.go
pkg/console/controllers/service/controller.go
pkg/console/controllers/upgradenotification/controller.go
pkg/console/operator/operator.go
pkg/console/operator/sync_v400.go
pkg/console/operator/sync_v400_test.go
pkg/console/starter/starter.go

Revert of https://github.com/openshift/console-operator/pull/899
The issue should be fixed by https://github.com/openshift/console-operator/pull/900

CONSOLE-4047: Console-operator should be internally using listers for fetching data

---

manifests/07-operator.yaml
quickstarts/consolequickstart-install-cryostat.yaml
quickstarts/impersonate-user.yaml
quickstarts/install-helmchartrepo-ns.yaml
quickstarts/install-serverless.yaml
quickstarts/jboss-eap7-with-helm.yaml
quickstarts/manage-helm-repos.yaml
quickstarts/node-with-s2i.yaml
quickstarts/quarkus-with-helm.yaml
quickstarts/quarkus-with-s2i.yaml
quickstarts/spring-with-s2i.yaml

https://github.com/openshift/console-operator/pull/868 missed couple of quickstarts. 

OCPBUGS-29547: Apply hypershift cluster-profile for ibm-cloud-managed

---

pkg/console/operator/sync_v400.go
pkg/console/telemetry/telemetry.go

OCPBUGS-33715: Cache organization ID when the ID changes

---

pkg/console/subresource/configmap/brand_ocp.go

OCPBUGS-35941: Bump documentationBaseURL to 4.17

---

manifests/03-rbac-role-cluster.yaml

CONSOLE-4163: Add RBAC for console to GET PackageManifests

---

bindata/assets/deployments/console-deployment.yaml
bindata/assets/deployments/downloads-deployment.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/console/subresource/deployment/deployment_test.go

[OCPBUGS-37408](https://issues.redhat.com/browse/OCPBUGS-37408)

OCPBUGS-37408:set required-scc for openshift workloads

---

OWNERS
quickstarts/OWNERS

NO-JIRA: Update OWNERS files

---

manifests/01-operator-config.yaml

Forgot to include this change in https://github.com/openshift/console-operator/pull/927

CONSOLE-4055: Have GettingStartedBanner enabled by default

---

pkg/console/controllers/healthcheck/controller.go

Bumping the retry duration for the healthcheck to 5 seconds, but its up for a discussion whats the proper time.
Also adding additional logging around the healthcheck.
/assign @dgoodwin

OCPBUGS-42534: Console-operator's route healthcheck should have longer retry

---

pkg/console/subresource/util/util.go

NO-JIRA: Remove unused code

---

quickstarts/OWNERS

/assign @spadgett @jhadvig 
/cc @vikram-raj @lokanandaprabhu @Lucifergene @invincibleJai

NO-JIRA: Update owners file: Update my github username)

---

pkg/console/subresource/configmap/brand_ocp.go

OCPBUGS-43837: Bump docs version

---

pkg/console/controllers/oauthclients/oauthclients.go
pkg/console/controllers/oauthclientsecret/oauthclientsecret.go
pkg/console/controllers/util/informers.go
pkg/console/controllers/util/informers_test.go
pkg/console/operator/sync_v400.go
pkg/console/subresource/consoleserver/config_builder.go

OCPBUGS-45222: Dont disable console when authConfig type is set to None

---

pkg/console/subresource/configmap/brand_ocp.go

OCPBUGS-48536: Bump documentationBaseURL to 4.19

---

quickstarts/enable-developer-perspective.yaml

ODC-7723: Add quick start to enable developer perspective

---

manifests/07-downloads-netobserv.yaml

Add netobserv CLI download link

NETOBSERV-2029: add netobserv ConsoleCLIDownload

---

test-e2e.sh
test/e2e/plugins_test.go

CONSOLE-4481: Add additional CSP test

---

pkg/console/telemetry/telemetry.go
pkg/console/telemetry/telemetry_test.go

OCPBUGS-58094: Consolidate telemetry values oscilation

---

quickstarts/consolequickstart-install-cryostat.yaml
quickstarts/enable-developer-perspective.yaml

- Update `configration` to `configuration`
- Update `Cluster Configuration` to `Cluster configuration` page
- Update Cryostat doc link

OCPBUGS-61383: Update QuickStarts typo and doc link
