openshift/console-operator

pkg/operator/util.go
Updated the manifests from `openshift-console-operator-test` namespace to `openshift-console`.  I was previously running side-by-side to the existing console, but we can now use the correct namespace.
@spadgett @jwforres
=> Update namespace to openshift-console

Dockerfile
Updating the root Dockerfile to use the correct CMD.  This file looks similar to the `tmp/output/build` `Dockerfile`, but has some additional requirements.
=> Fix CMD in Dockerfile

Dockerfile
Matching up with labels we put on `console` and other `operators`.
=> Add additional labels to Dockerfile

Dockerfile, deploy/02-sa.yaml, deploy/03-rbac-role.yaml, deploy/04-rbac-rolebinding.yaml, deploy/05-operator.yaml
Adjusting `rbac.yaml` for deploying the operator.  `operator-sdk up local` permissions were a little more relaxed, deploying the operator via `oc create -f deploy/*` requires these changes for the oauth client & route to be created.
=> Update rbac for oauth and route creation

manifests/image-references
I'm seeing this file crop up in the `/manifests` dir, so creating it, but need to verify its purpose before removing WIP.
An example:
- https://github.com/openshift/cluster-image-registry-operator/blob/master/deploy/image-references
=> Add manifests/image-references file

examples/cr.yaml, manifests/05-operator.yaml, manifests/image-references, pkg/apis/console/v1alpha1/types.go, pkg/operator/deployment.go, pkg/operator/util.go
The operator itself is fine, but the image for the console was not correctly referenced in `/manifests/image-references`. 
- The IMAGE env var is now passed in `/manifests/05-operator.yaml`
- The operator does not handle `image:version` on the deployment, CVO handles versioning
=> Correct image references for origin-console

pkg/console/operator/operator.go, pkg/console/starter/starter.go
Previously, the code incorrectly called the OAuth client authorizations informer.
Update the informer and client types to be more consistent.
Signed-off-by: Monis Khan <mkhan@redhat.com>
=> Use correct informer for OAuth clients

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/util/util.go
A block from the sync loop will now look like this:
This PR only adds a few log statements & cleans up formatting (`\n`, consistent lower case, verbiage, etc).
=> Improve sync loop logging feedback

pkg/console/operator/sync_v400.go, pkg/console/subresource/route/route.go
The sync loop should also ensure the correctness of each resource, at least in all of the fields that matter for a running console. This adds a `validate()` fn to the route `sync`, which will only trigger an `update` if `changed` is `true`.
=> Add Validate() fn to route

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/service_ca.go, pkg/console/subresource/deployment/deployment.go
Annotate a config map to hold the service-ca.crt for the Prometheus proxy.
Requires https://github.com/openshift/console/pull/960
See https://github.com/openshift/service-serving-cert-signer#openshift-service-serving-cert-signer-operator
/cc @benjaminapetersen @enj
=> Inject service-ca.crt into the console pod from a config map

hack/test-e2e.sh, pkg/api/api.go, pkg/testframework/clientset.go, pkg/testframework/config.go, pkg/testframework/framework.go, test/e2e/main_test.go, test/e2e/managed_test.go
Adding e2e tests for console-operator *Managed* state.
Added the suggested check if the console-operator is up. Then The test will remove the console-operator deployment and will check if the deployment is recreated.
to launch the tests, call `make test-e2e`, whre the **KUBECONFIG** envar has to be set
@benjaminapetersen PTAL
=> Console operator e2e test - Managed state

manifests/05-operator.yaml, pkg/console/subresource/deployment/deployment.go
Story: https://jira.coreos.com/browse/CONSOLE-960
@benjaminapetersen pointed out old [HELM operator](https://github.com/benjaminapetersen/console-helm-operator/blob/master/helm/output/console/templates/deployment-console.yaml#L56-L62) so I'm not sure the resource limits I've set in this PR are proper.
@spadgett PTAL
=> Add Resource Limits to Deployment

pkg/api/api.go, pkg/testframework/clientset.go, pkg/testframework/console.go, pkg/testframework/framework.go, pkg/testframework/logs.go, test/e2e/managed_test.go, test/e2e/removed_test.go, test/e2e/unmanaged_test.go
Adding Unmanaged and Removed test cases.
Each tests is testing several resources from the "openshift-console" namespace - Deployment/ConfigMap/Service/Route and their availability/unavailability for each operator state.
Also added `logs.go` that I've get [from](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/testframework/logs.go) to get better logs.
=> Add e2e test for console operator Unmanaged and Removed states

README.md, examples/05-operator-alt-image.yaml, manifests/01-namespace.yaml, manifests/02-rbac-role.yaml, manifests/03-rbac-rolebinding.yaml, manifests/04-config.yaml, manifests/04-sa.yaml, manifests/05-operator.yaml, pkg/api/api.go, pkg/testframework/console.go, pkg/testframework/framework.go
https://jira.coreos.com/browse/CONSOLE-1206
cc @benjaminapetersen @enj @jhadvig
=> Move console operator into a separate namespace

pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/configmap/service_ca_test.go, pkg/console/subresource/deployment/deployment_test.go, pkg/console/subresource/oauthclient/oauthclient_test.go, pkg/console/subresource/route/route_test.go, pkg/console/subresource/secret/secret_test.go, pkg/console/subresource/service/service_test.go, pkg/console/subresource/util/util_test.go
This is one example for unit tests in the configmap pkg of the console operator.
=> Unit tests Console Operator

pkg/testframework/framework.go, test/e2e/main_test.go, test/e2e/managed_test.go, test/e2e/removed_test.go, test/e2e/unmanaged_test.go, test/e2e/util.go
@benjaminapetersen adding promised tests.
Per our discussion, the tests are editing the resources separately, not bulk, since they have different semantics for the test.
The tests are testing ConfigMap, Service and Route. I've skipped the Deployment since the console operator is not managing changes user makes to it(which is kinda weird?).
Also made the `getResource()` public -> `GetResource()`, so it can be used on different places + now it's returning runtime.Object so different fields object field can be accessed.
PTAL
=> Test editing resources in Managed and Unmanaged console-operator state

manifests/00-oauth.yaml, manifests/02-rbac-role.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, pkg/console/subresource/route/route.go, pkg/console/subresource/route/route_test.go, pkg/console/subresource/service/service.go, pkg/console/subresource/service/service_test.go
Per an email conversation w/@spadgett.
Changing the `Deployment` name to `console` is consistent with the other resources & eliminates the extra `ConsoleShortName` variable.
=> Rename Deployment openshift-console to console

manifests/02-rbac-role.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/testframework/console.go
- handles values set on console config
- handle values set on operator config
- report public hostname on status
- oauth team dependent on this update
=> Honor configs & report public hostname on status

Dockerfile.rhel7, Makefile, hack/lib/build/binaries.sh, hack/lib/constants.sh, pkg/cmd/version/cmd.go, pkg/console/subresource/configmap/brand_ocp.go, pkg/console/subresource/configmap/brand_okd.go, pkg/console/subresource/configmap/configmap.go
Add Goflag option to define branding at build time.  Docker rhel file has been updated to provide ocp branding.
Usage: ADDITIONAL_GOTAGS="ocp" make WHAT="cmd/console" 
$ console version
ConsoleOperator v0.0.1
Git Commit: 6cf43775
Build Date: 2019-02-05T20:08:03Z
Current Brand Setting: ocp
Tag option: ocp
This solution uses tags in the build process.
Additionally, updated the console version helper tool to show current Git Commit value, build date, and the brand setting.
=> Add Goflag option to define branding at build time

pkg/console/subresource/configmap/brand_ocp.go
Update ocp DEFAULT_DOC_URL to https://docs.openshift.com/container-platform/4.0/ 
Only affects the ocp container build.
The console container has a small bit of validation on the doc url that simply requires a trailling `/`. The full doc link we have for ocp is `https://docs.openshift.com/container-platform/4.0/welcome/index.htm`.  Adding a trailling `/` will 404, but cutting the `welcome/index.htm` will automatically trigger a redirect to the correct location.
@zherman0
=> Update ocp DEFAULT_DOC_URL

pkg/api/api.go
Global config & operator config should be named `cluster`, not `console`.  
console.config.openshift.io - cluster
console.operator.openshift.io - cluster
(Note ClusterOperator is still named `console`).
=> Fix config singleton names

pkg/console/starter/starter.go
Lists on the configs should ensure they only grab configs explicitly named `cluster`:
- `console.config.openshift.io - cluster`
- `console.operator.openshift.io - operator`
=> List configs by name explicitly

manifests/07-operator.yaml
The director for # of replicas for an operator seems to be:
- Other operators depend on you: `replicas: 2`
- Other operators do not depend on you: `replicas: 1`
If the operator goes down & does not block another operator from recovering, a higher number of replicas is not needed 
- `thing you block, if len() > 0 { replicas = 2 } else { replicas = 1 }`. 
- Also `if have web facing traffic replicas >= 2 else replicas 1`.
I almost updated leader election to:
```
apiVersion: operator.openshift.io/v1alpha1
kind: GenericOperatorConfig
leaderElection:
namespace: openshift-console
disabled: true
authentication:
disabled: true
authorization:
disabled: true
```
but there may be cases where 2 operators could still be deployed.  Perhaps during an upgrade? In this case, it seems safer to leave leader …
=> Set console-operator replicas to 1

examples/05-operator-alt-image.yaml
If we are going to keep this file for development reference, it should contain better information & not be pinned to a specific (very old) version of one of my own dev images.
I'd either update it for reference, or just delete it & refer to the README.
=> Update examples/05-alt-image.yaml to include better dev info

examples/cr-console.operator.config.yaml, hack/test-unit.sh, manifests/00-crd-operator-config.yaml, pkg/console/subresource/configmap/configmap_test.go
This PR adds: 
1) Validation in the CRD to test that well formed URLs are supplied
a) https://www.redhat.com:8080/logout.html is valid
b) www.redhat.com (no http) is invalid
2) The validation also checks for trailing slash on the DOC link
a) https://doc.com/     is vaild
b) https://doc.com/doc    is invalid
3) Validate that the brand is one of the 5 acceptable values: ocp|origin|okd|dedicated|online
4) Validate that managedState is one of the 4 possible values: Managed|Unmanaged|Removed|Forced
5) Unit test for builds with the "ocp" tag set
6) There is no E2E test for URL at the moment because I have not figured out how to load/test values that are being detected at the oc api level
7) I had code in the config map to test URLs but have removed it since it duplicated the validation being …
=> Validate URLs from the CR file and additional unit tests for ocp tag

manifests/00-crd-operator-config.yaml
This will need to be rebased when PR164 goes through.
This PR adds:
1. Validation in the CRD to test that well formed URLs are supplied for DOC link
a) https://www.redhat.com:8080/ is valid
b) http://www.redhat.com  is invalid (no http)
2. The validation also checks for trailing slash on the DOC link
a) https://doc.com/     is vaild
b) https://doc.com/doc    is invalid
3. Validate that the brand is null or one of the 6 acceptable values: ocp|origin|okd|dedicated|online|azure
4. Validate that managedState is one of the 4 possible values: Managed|Unmanaged|Removed|Forced
=> Validate properties in CRD

pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/configmap/service_ca_test.go, pkg/console/subresource/deployment/deployment_test.go, pkg/console/subresource/oauthclient/oauthclient_test.go, pkg/console/subresource/route/route_test.go, pkg/console/subresource/secret/secret_test.go, pkg/console/subresource/service/service_test.go, pkg/console/subresource/util/util_test.go
Change unit test to use cleaner error output.  Currently any error from unit test failing shows a large blob of data that one must scour through to see what has failed.  This update uses the go-test/deep pkg to only show what has failed in a clean, simple output.
Before:
After:
=> Change unit test to use cleaner error output

manifests/07-operator.yaml
All operator created pods should be using digest based UIDs, so `imagePullPolicy: Always` is not appropriate.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1685233
=> Bug 1685233: Switch to `imagePullPolicy: IfNotPresent`

pkg/console/operator/sync_v400.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/route/route.go
Bug 1686133
The console should be available when one pod is available and the route has been accepted. For the console, this means that the route ingress that matches `Route.Spec.Host` should have an `Admitted` condition of `true`. 
([link 1686133](https://bugzilla.redhat.com/show_bug.cgi?id=1686133))
@spadgett 
@deads2k
=> Bug 1686133: Fix operator availability to include route availability check

pkg/console/subresource/deployment/deployment_test.go
/assign @zherman0 @spadgett 
This is trivial, but I think we want certainty around correct reporting of Ready for `Status.Condition.Available` so it's worth a test.
=> Add unit tests for deployment IsReady() func

pkg/console/subresource/route/route_test.go
This adds tests for a variety of possible scenerios for the new `IsAdmitted()` func for `routes`.
This is important for correctly determining `Status.Condition.Available`.
/assign @spadgett @zherman0
=> Add test for route IsAdmitted()

manifests/07-downloads-deployment.yaml, manifests/08-downloads-service.yaml, manifests/09-downloads-route.yaml, manifests/image-references
We need to support the ability to download clients (`oc`) from the cluster when an install is successful.  With this commit, I'm adding a new Deployment for serving the binary from the cli image referenced
from the release image.  That way, the provided `oc` is the appropriate version for the current cluster version.  I've set `replicas` to two to support continued availability during rolling updates.
The Python here-document approach is based on openshift/ci-operator@95a41a39 (openshift/ci-operator#35).  The script creates a scratch directory to serve from, and populates it with the `oc` binary (via a symlink).  It also creates zip and tar versions, so users can do things like:
```console
$ wget https://downloads-openshift-console.apps.wking.devcluster.openshift.com/amd64/linux/oc.zip
$ …
```
=> manifests: Serve oc from within the cluster

pkg/console/starter/starter.go
I thought certain this was part of the PR that fixed the missing master url on our configmap (#173).
=> Add infrastructures config to operator related objects

pkg/console/operator/status.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go
`Spec.UnsupportedConfigOverrides` essentially should allow a user to replace our configmap.  This should only be needed as an escape hatch if something terrible has gone wrong.
When used, the `ClusterOperator` for `Console` will record the config overrides under `Status.Conditions.Upgradable`.  This is consistent with what is done by [kube-apiserver-operator](https://github.com/openshift/cluster-kube-apiserver-operator).
ClusterOperator:
`oc get clusteroperator/console -w -o yaml`
=> Support Spec.UnsupportedConfigOverrides

Dockerfile.rhel7
Remove hardcoded amd64 from Dockerfile for MultiArch builds.
=> Remove hardcoded amd64 from Dockerfile for MultiArch builds

pkg/console/subresource/route/route.go
We don't use this function.  We depend on changes to the `route` coming from the router, so can't blindly apply route like other resources.
=> Remove ApplyRoute() func

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/oauthclient/oauthclient.go, pkg/console/subresource/oauthclient/oauthclient_test.go, pkg/console/subresource/route/route.go
Selects `host` from the `admitted` `ingress` on the route, if it exists. Else, fallback to `spec.host` as we have been doing in the past.
[CONSOLE-1336](https://jira.coreos.com/browse/CONSOLE-1336)
/assign @spadgett @jhadvig @zherman0
=> Select host from admitted ingress, else fall back to route.spec.host

manifests/07-downloads-deployment.yaml, manifests/07-operator.yaml, pkg/console/subresource/deployment/deployment.go
The previous attempt of `/dev/termination-log` isn't giving a good result.  Use the pod log as the termination
=> report last few log lines as error

Dockerfile, manifests/03-rbac-role-ns-openshift-config-managed.yaml, manifests/04-rbac-rolebinding.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go
Update the default behavior of branding so that the one and only docker file now builds `ocp` instead of `okd`.
If the user instead wants to manually build openshift with `go build` or `make build`, that process will default to `okd`.
=> Revise branding mechanism for Console Operator

pkg/console/operator/sync_v400.go, pkg/console/subresource/route/route.go
Everywhere else we use `GetCanonicalHost()`, no longer `Route.Spec.Host`.  However, I am looking to see if there is a significant timing difference between these values being set.  That said, I don't believe `Route.Spec.Host` is reliable.
=> Update SyncRoute() to look for host on ingress, not route.spec.host

manifests/07-operator.yaml
Default logs should not be `debug` (developer centric), should be `info`.  I hesitated to want to reduce this earlier on, but for development we should all be deploying our own `deployment` of a custom `operator` image based on feature branches anyway, so it doesn't make sense to leave our log levels so high.
This doesn't affect our explicit `logrus` based logging.  We will have to handle that when we swap to `klog`, and ensure the update uses `debug`,`info`, etc.
=> Reduce default log level

manifests/02-namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

pkg/console/operator/operator.go
- ManagementState:Removed should delete all confgmaps, including `service-ca` 
- ManagementState:Managed should recreate the `service-ca` configmap
Note that we do not own the `downloads` deployment, so we won't add this to `deleteAll()`.
=> Delete service-ca configmap when ManagementState:Removed

manifests/03-rbac-role-ns-openshift-config-managed.yaml, manifests/04-rbac-rolebinding.yaml, manifests/08-config-public.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/configmap/service_ca.go, pkg/console/subresource/configmap/service_ca_test.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, pkg/testframework/framework.go
The global config resource is not readable by normal users. Add a public
config map that has the console URL so it can be discovered by all
authenticated users.
=> Add public console config to publish console URL

pkg/console/operator/operator.go
To prevent hot-looping in `Removed` state, we need to add condition check (added the check to the `Unmanaged` state as well)
Tested the change locally and the hot-looping is gone, also e2e are green
Bug: https://jira.coreos.com/browse/CONSOLE-1430?filter=-1
@benjaminapetersen fyi
=> Check if OAuth is already updated when in Removed state to prevent hotloop

manifests/01-operator-config.yaml, manifests/07-operator.yaml, pkg/cmd/operator/cmd.go, pkg/console/operator/operator.go
There is an email from @damemi titled `[aos-devel] Notice: Operator configs should be managed by the CVO` instructing we should make this change.
- Includes the `create-only` annotation
- `CRD` is lexicographically ordered `00-`, `CR` is `01-`.  This is because the CR should be created after the CRD.  The CR being at the same level as the `oauthclient` should be irrelevant.
- Removes our `defaultConsoleOperatorConfig()`, which was used at the start of the `sync` loop if the `GET` on our `config` was a `404`.  The CVO will now be our single source of truth providing the config, we will simply err until it gets recreated.
=> Use CVO to create operator config

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go
Refactor how the config map for console is created in terms of what has priority over each config map.  In our case, we are now defining this order:
1. Default values (i.e. Brand = okd)
2. console-config from openshift-config-managed namespace
3. config map from operator config
4. UnsupportRaw which usurps everything else
Also added new unit test for to cover all 1,2,3, not 4 yet.
=> Refactor priotrity of config maps for console

test/e2e/branding_test.go, test/e2e/logging_test.go
E2E tests specific to branding.
1) Check that we can set brand via operator config
2) Check that setting the console config in the openshift-config-managed namespace is honored when a specific brand is chosen.
=> E2E test specific to branding

pkg/console/operator/status.go, pkg/console/operator/sync_v400.go
We should show the version as-is instead of stripping everything after
the `-`. Note for release versions, the version number will be short
like `4.1.1`. For prerelease builds, stripping content after `-` removes
the unique part of the version number.
We should also show informative messages in the cluster operator status
even when there are no errors.
=> Improve cluster operator status reporting during upgrades

pkg/testframework/console-operator.go, test/e2e/branding_test.go, test/e2e/logging_test.go, test/e2e/managed_test.go, test/e2e/providers_test.go, test/e2e/removed_test.go, test/e2e/unmanaged_test.go
Add WaitForSettledState func to check Operator Config before progressing to next test.
/assign @jhadvig @zherman0
=> Add WaitForSettledState func to check Operator Config before progressing

manifests/03-rbac-role-ns-openshift-config.yaml, manifests/04-rbac-rolebinding.yaml, pkg/api/api.go, pkg/console/clientwrapper/without_secret.go, pkg/console/errors/custom_logo_errors.go, pkg/console/errors/custom_logo_errors_test.go, pkg/console/operator/operator.go, pkg/console/operator/status.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/brand_custom_logo.go, pkg/console/subresource/configmap/brand_custom_logo_test.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, test/e2e/brand_customization_test.go, test/e2e/branding_test.go
- based on #220 by @zherman0 
- with some `clientwrapper` magic by @enj 
- unsquashed to maintain original authorship of commits
Feature:
- Provide a `Custom Product Name` and `Custom Logo` to be displayed in the console via operator configuration.
Requires additional RBAC to run:
- Pull the branch & have a dev cluster handy
- Disable CVO so you can deploy your custom operator image
`oc scale deployment cluster-version-operator --replicas 0 --namespace openshift-cluster-version`
- Docker build `docker build -t quay.io/<you>/console-operator:latest .`
- Docker push `docker push quay.io/<you>/console-operator:latest`
- Apply the additional necessary Rolebinding `oc apply -f manifests/04-rbac-rolebinding.yaml`
- Apply the additional Role `oc apply -f …
=> Custom brand revisions

pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/brand_custom_logo.go, pkg/console/subresource/configmap/brand_custom_logo_test.go
- Ensure removing custom logo from operator config allows for custom-logo configmap to be deleted
/assign @jhadvig @zherman0
=> Allow custom-logo configmap to be removed

manifests/03-rbac-role-cluster.yaml, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Adding console support for cluster proxy. If the Proxy CRD is set, operator will read them and set proper environment variables inside the console container.
FollowUp should be setting the proxy on the console server http client [as does in.](https://github.com/openshift/console/pull/1249)
/assign @benjaminapetersen @zherman0 
Story: https://jira.coreos.com/browse/CONSOLE-1440
=> Add proxy support

manifests/00-crd-extension-console-log-link.yaml, manifests/03-rbac-role-cluster-extensions.yaml
Resolves https://jira.coreos.com/browse/CONSOLE-1547
=> Add console extension manfiest for ConsoleExternalLogLinks CRD

Dockerfile
This modifies the Dockerfile to add the build support for archs other than amd64, based on the commit: https://github.com/openshift/console-operator/commit/99e70b78192e8b7c7618a3deab2659a2f0b32d62
=> Adding build support for archs other than amd64

pkg/console/operator/status.go
We should not directly set the `Condition. LastTransitionTime` as this can interfere with the bookkeeping of `ClusterOperatorStatusController`.
=> Remove LastTransitionTime from status.conditions

examples/cvo-manage-operator.yaml, examples/cvo-unmanage-operator.yaml
We need to add the group, since the overrides are not accepted without it.
=> Add group to managed and umanaged ClusterVersion overrides

pkg/console/operator/operator.go, pkg/console/operator/status.go, pkg/console/starter/starter.go
Adds the `ManagementStateController` to handle `status` messages on the operator rather than handle these manually.  This ensures we are consistent with other operators.  Note that it does not actually handle `ManagementState` in terms of sync loop.
=> Add ManagementStateController

pkg/console/operator/status.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/deployment/deployment.go, test/e2e/framework/console-operator.go
Depends on #269 & #271 & will be rebased once it is merged.
Re [bugzilla 1740387](https://bugzilla.redhat.com/show_bug.cgi?id=1740387) - partial fix.
WIP until rebase.
@jhadvig I think #253 can be rebased on this change now as we no longer need the `ConditionsDefault()` as a dependency for the rest of the statuses.
@spadgett fyi
This is should handle the rest of the status transition.
=> Update Available condition to use handlers

pkg/console/operator/operator.go
Based on https://github.com/openshift/cluster-authentication-operator/pull/142#issue-293463578 we should handle degraded condition more carefully, meaning update only after there are changes.
/assign @benjaminapetersen @zherman0
=> Bug 1724977: Invalid customization values should not make operator hotloop

pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/trusted_ca.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Story: https://jira.coreos.com/browse/CONSOLE-1669
The `volumes` and `volumeMounts`  are set properly but the `merger.Merge()` in the `configmap.go` is for some reason is dropping the `TrustedCA` variable.
=> Add support for proxies TrustedCA

manifests/07-downloads-deployment.yaml
Instead of setting up signal forwarding between the shell process and Python, just drop the shell process entirely after it has served its purpose.  This might help with SIGTERM and SIGKILL handling; currently this Pod occasionally [takes ~600ms to drain][1]:
I0826 19:02:54.769125   25457 update.go:89] pod "downloads-769755ddf9-jbhdw" removed (evicted)
which may have eventually resulted [in][3]:
Aug 26 19:05:01.689 E clusteroperator/machine-config changed Degraded to True: RequiredPoolsFailed: Unable to apply 0.0.1-2019-08-26-172415: timed out waiting for the condition during syncRequiredMachineConfigPools: error pool master is not ready, retrying. Status: (pool degraded: false total: 3, ready 1, updated: 1, unavailable: 1)
I'm not entirely clear on whether this `exec` will fix the issue, …
=> Bug 1745772: manifests/07-downloads-deployment: Exec Python for signal handling

pkg/console/operator/operator.go, pkg/console/operator/status.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/route/route.go
- Expands from `Progressing`, `Degraded`, `Available` as generic conditions into a plethora of specific `Types`, using these as `Suffix` for categorization & relying on the `ClusterOperatorStatusController()` to condense back down on the `clusteroperator`.  
- Provides specific `Reasons` when state is flipped (with error as `Message`)
New example:
```
- lastTransitionTime: "2019-08-26T19:18:52Z"
status: "False"
type: ServiceCASyncProgressing
- lastTransitionTime: "2019-08-28T15:47:52Z"
message: custom logo sync source update error
reason: FailedSyncSource
status: "True"
type: CustomLogoDegraded
- lastTransitionTime: "2019-08-28T15:47:52Z"
message: console route is not admitted
reason: FailedAdmittedIngress
status: "True"
type: RouteAvailable
```
@jhadvig @spadgett
=> Bug 1740387: Better Progressing & Degraded condition handling & names

pkg/console/starter/starter.go
Related to #254 & #276 we should list the proxy config with the other configs we depend on.
/assign @jhadvig  
per your slack comment!
=> Add proxy config to ClusterOperator status related objects

pkg/console/operator/operator.go
=> Use api's ConfigResourceName variable instead the plain string

manifests/07-downloads-route.yaml
Following [the pattern set by other OpenShift routes][1].  [The 4.1 docs][2] around this don't go into much detail on `insecureEdgeTerminationPolicy`, spending the time on HTTP Strict Transport Security (HSTS) instead.  Since HSTS client support is optional, and since we should be using https:// download links anyway, I haven't bothered with the HSTS annotation.
[The 3.11 docs][3] go into more detail on `insecureEdgeTerminationPolicy`, including an example with both edge and redirect termination together.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1746966
[2]: https://docs.openshift.com/container-platform/4.1/networking/routes/route-configuration.html#nw-enabling-hsts_route-configuration
[3]: https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secur …
=> Bug 1746966: manifests/07-downloads-route: Set redirect termination

manifests/07-downloads-deployment.yaml
Docs [here][1].  Precedent [here][2].  Doesn't seem all that likely that this container will take long to come up or hang afterwards, but doesn't hurt to check.
[1]: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
[2]: https://github.com/openshift/release/commit/866514e635edd5b23939cc6f8eb34da0e5ba1d5f#diff-ed49f06f2ad46798c08292c4aecccee2R65-R75
=> manifests/07-downloads-deployment: Add container probes

manifests/07-downloads-deployment.yaml
A second attempt to resolve the slow terminations discussed in 777a02aa0f (#275).  This commit is a bit more direct, and matches precedent [here][1] and [here][2].
[1]: https://github.com/openshift/ci-operator/commit/f20a45fe7aa2eac495dfb3ff5c0417f1db4b745b#diff-53826ade74ebb51dda06c1eb3f69cac9R100
[2]: https://github.com/openshift/release/commit/866514e635edd5b23939cc6f8eb34da0e5ba1d5f#diff-ed49f06f2ad46798c08292c4aecccee2R82
=> Bug 1745772: manifests/07-downloads-deployment: Set terminationGracePeriodSeconds

pkg/console/operator/status_test.go
Adds a unit test for each of the "public" functions for handling operator statuses.  
The main value is in the `TestHandleProgressingOrDegraded()` to ensure the handling of multiple conditions is correct (ref #285).  
=> Add unit tests for condition handlers

test/e2e/framework/framework.go
Just a minor fix. Still investigating why the `TestCustomBrand` e2e is failing.
=> Get correct ConfigMap name in e2e test helper

manifests/07-downloads-deployment.yaml, manifests/07-operator.yaml, manifests/image-references
This gets us (currently) oc binaries built for Windows and Darwin as well ([cli-artifacts Dockerfile][1]).
While I was bumping cli -> cli-artifacts, I dropped docker.io from the other image references.  Compare openshift/machine-config-operator#750 for that commit.  I can spin that out into its own PR if you want to review separately.
[1]: https://github.com/openshift/oc/blob/58a901446e84410b2b754575fac1f45117f6eece/images/cli-artifacts/Dockerfile.rhel#L7
=> manifests/07-downloads-deployment: Serve from cli-artifacts

manifests/0000_90_console-operator_01_prometheusrbac.yaml, manifests/0000_90_console-operator_02_servicemonitor.yaml, manifests/02-namespace.yaml, manifests/04-rbac-rolebinding-cluster.yaml, manifests/04-rbac-rolebinding.yaml, manifests/05-config.yaml, manifests/05-service.yaml, manifests/07-operator.yaml, pkg/console/operator/sync_v400.go
We should expose /metrics to cluster monitor for both console & console-operator.  Working out the details of this in this PR.
- console-operator via library-go already has a `/metrics` endpoint running, its just a matter of wiring it up
- console does not have a `/metrics` endpoint at this time.  This may require a follow on set of PRs, one to the console to enable a `prom-client` for the console server & collect at least basic heap metrics
Validate that the operator is responding to the `/metrics` endpoint via:
`curl --insecure -H "Authorization: Bearer $(oc whoami --show-token)" https://$(oc get route metrics --template "{{.spec.host}}"/metrics) | grep console_url`
Validate that the `console_url` metric is being reported in the monitoring UI: 
`open $(oc get route prometheus-k8s -n …
=> Expose metrics

pkg/console/operator/operator.go, pkg/console/starter/starter.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
The console deployment has not been rollout upon changes made to the Proxy CR.
+ refact a the Proxy codebase
Tested manually on latest cluster and it's fixing the issue.
FYI @spadgett
=> Bug 1753672: Redeploy console deployment upon proxy changes

manifests/00-crd-extension-console-link.yaml
Adding the `NamespaceDashboard` location
Story: https://jira.coreos.com/browse/CONSOLE-1710
@rhamilto FYI
=> Update operator for project link API changes

test/e2e/framework/clientset.go, test/e2e/framework/framework.go, test/e2e/framework/utils.go, test/e2e/proxy_test.go
Test scenario: 
- e2e test for setting `NoProxy` & `HTTPProxy` & `HTTPSProxy` to the Proxy CR and checking the new rolledout console deployment pod for corresponding environment variables (`NO_PROXY` & `HTTP_PROXY` & `HTTPS_PROXY`) 
=> Proxy e2e test

test/e2e/proxy_test.go
Have seen the e2e test for the proxy flaking lately with following error:
```
unable to find environment variable: wanted NO_PROXY
```
Need to do some investigation, so marking as WIP
=> Fix NO_PROXY flake

manifests/07-downloads-deployment.yaml
It's possible that this process would run as PID 1 in a PID namespace, and [PID 1 has special handling][1]:
> Only signals for which the "init" process has established a signal handler can be sent to the "init" process by other members of the PID namespace.
That's unlikely to be important for termination, because CRI-O will be TERMing the process from outside the pod's PID namespace.  With the coming PID-namespace sharing [2], you could set this container process
up to not be PID 1 in any namespace.
But regardless, gracefully exiting when we're asked to is polite behavior.  In the future, we might want to add something here to delay exiting until we have finished serving any ongoing downloads (or at least give them a fair shot at finishing), but clients can always retry any downloads that …
=> manifests/07-downloads-deployment: Catch and exit on TERM

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/status/status.go, pkg/console/status/status_test.go
Make status handlers standalone helper funcs that can be used across controllers
This makes them useful now that we want to break off into separate controllers. See:
- #306 CLIDownloadsController 
- #305 ServiceSyncController 
/assign @jhadvig @spadgett
=> Make status handlers standalone helper funcs

pkg/console/operator/operator.go, pkg/console/starter/starter.go
Reorganize args to NewConsoleOperator() to fit client/informer sets together.
This will make it easier to extract out components into separate controllers. 
=> Reorganize args to NewConsoleOperator func

manifests/00-crd-consoleclidownloads.yaml, manifests/00-crd-consoleexternalloglinks.yaml, manifests/00-crd-consolelinks.yaml, manifests/00-crd-consolenotifications.yaml, manifests/00-crd-consoleyamlsamples.yaml
They shall return to us!
To make @deads2k happy 😄 
/cc @spadgett @jhadvig 
TODO as follow-up:
=> Temporarily return extension CRDs from cluster-config-operator to our Manifests dir

hack/test-unit.sh, manifests/03-rbac-role-cluster-extensions.yaml, manifests/03-rbac-role-cluster.yaml, pkg/api/api.go, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go
https://jira.coreos.com/browse/CONSOLE-1423
Adding ConsoleCliDownloads controller that will take care of ConsoleCliDownloads `oc` binaries for different platforms.
=> Add ConsoleCliDownloads controller

pkg/console/controllers/service/controller.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go
Split SyncService() func into separate NewServiceSyncController() from main operator control loop.  
Rather than one mega controller doing all the things, we should have many smaller controllers doing specific things.  The first step will be to split off by resources as this is fairly simple.  However, some resources, such as the Deployment, may be split into several if it makes sense.
This `controller` does not make use of `monis.app/go/openshift/operator` boilerplate, thus it implements all of the following:
```golang
func sync() {}
func Run() {}
func runWorker() {}
func processNextWorkItem() {}
func newEventHandler() {}
``` 
which, for the most part, is pretty generic.  
@jhadvig FYI, this may be helpful to look at for the CRDs control loop.
=> NewServiceSyncController

pkg/api/api.go, pkg/console/controllers/clidownloads/controller.go, test/e2e/framework/clientset.go, test/e2e/framework/console-operator.go, test/e2e/framework/framework.go, test/e2e/managed_test.go, test/e2e/unmanaged_test.go, test/e2e/util.go
Adding the TCs to the Managed, Unmanaged and Removed test suites, since the testing scenario is pretty much the same as other resources.
Due to the wrong regexp on the ConsoleCLIDownloads CRD the added e2e will fail until it will be fixed.
/hold
=> Add e2e test for oc and odo ConsoleCLIDownloads CRs

pkg/console/controllers/service/controller.go, pkg/console/starter/starter.go, test/e2e/framework/console-operator.go, test/e2e/framework/utils.go, test/e2e/removed_test.go, test/e2e/unmanaged_test.go
The issue of the failing Unmanaged e2e tests was that the new ServiceController haven't picked up changes in the consoleoperator config, eg: change from `Unmanaged` to `Managed` state.
Due to this the `console` service has not been recreated and the console pods could not start since cause of that the `console-serving-cert` secret was missing.
Also adding the `StandardSetup` call from https://github.com/openshift/console-operator/pull/329, which this PR shoud replace.
Also removing the skipping of the failing tests, which should replace https://github.com/openshift/console-operator/pull/336 since there is no point to have two PR for that.
=> Missing service informer

pkg/console/subresource/deployment/deployment.go
We have gotten some requests for a little more detail in err messages when the deployment is not available/ready/etc.  Stating some `x of y` data should improve this.
Also eliminates logging when in a good state as this is likely just noise.
=> Improve deployment state errors

test/e2e/framework/framework.go
We haven't been consistent with the resources that we are `GET`ting and `DELETE`ing
=> Unify testing resources in e2e tests

pkg/console/operator/operator.go
If there is a `err`, then we should error out...
/assign @beanh66 
@spadgett FYI
=> Remove proxyConfig NotFound check

hack/test-unit.sh, pkg/api/api.go, pkg/console/controllers/resourcesyncdestination/controller.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Syncing the `router-ca` from `openshift-config-managed` namespace to `openshift-console` namespace and pasing to the `console` deployment.
Will update the unit tests after the first round of review to avoid unnecessary rewrites.
=> Bug 1764704: Sync router-ca to the console namespace

pkg/console/metrics/metrics.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, test/e2e/framework/config.go, test/e2e/framework/framework.go, test/e2e/metrics_test.go
An e2e test to validate that the `/metrics` endpoint on the `operator` responds with an expected output.
=> Bug 1764313: 4.3 console_url is no longer reported on metrics endpoint (fix, with e2e test)

pkg/console/operator/operator.go
The `DELETE` of the `service` is handled in the `ServiceSyncController` now.  Remove the redundant attempt to delete the service. 
=> Remove redundant service delete

test/e2e/extensions_crud_test.go, test/e2e/framework/clientset.go
Since we are loading these resources from generated YAML in `/vendor`, lets make sure we can `CREATE`/`DELETE` one of each.
/assign @spadgett @jhadvig
=> Add CRUD (create,delete) tests for console extension resources

test/e2e/downloads_test.go, test/e2e/framework/framework.go, test/e2e/metrics_test.go, test/e2e/removed_test.go, test/e2e/util_http.go
```bash
go test -run TestDownloadsEndpoint -count 1
checking for console-operator availability
found operator deployment
link for Download oc for Linux 200 OK (https://console-openshift-console.apps.bpetersen.devcluster.openshift.com/amd64/linux/oc.tar)
link for Download oc for Mac 200 OK (https://console-openshift-console.apps.bpetersen.devcluster.openshift.com/amd64/mac/oc.zip)
link for Download oc for Windows 200 OK (https://console-openshift-console.apps.bpetersen.devcluster.openshift.com/amd64/windows/oc.zip)
PASS
ok  	github.com/openshift/console-operator/test/e2e	5.274s
```
=> Add e2e test for oc downloads links

manifests/07-operator.yaml
We have several endpoints we can hit on the operator:
```
{
"paths": [
"/apis",
"/healthz",
"/healthz/log",
"/healthz/ping",
"/livez",
"/livez/log",
"/livez/ping",
"/metrics",
"/readyz",
"/readyz/log",
"/readyz/ping",
"/readyz/shutdown"
]
}
```
So adding both `/healthz` and `/readyz` probes.  Initial prob config is basically the same as that of the `console` `deployment` otherwise.
/assign @spadgett  @jhadvig 
To manually test these endpoints, do something like `oc create -f` on:
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
name: console-operator-route-for-testing
namespace: openshift-console-operator
spec:
port:
targetPort: https
tls:
insecureEdgeTerminationPolicy: Redirect
termination: passthrough
to:
kind: Service
name: metrics
weight: 100
wildcardPolicy: None
``` …
=> Add liveness and readiness probes to console operator

manifests/07-downloads-deployment.yaml, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go, test/e2e/downloads_test.go
In order for console-operator deployment to succeed, cli-artifacts needs to be available on all arches for downloads-openshift-console. However, in that case, /usr/bin/oc (inherited from cli) is a native binary, and we want to provide all primary Linux architectures to match those on mirror.openshift.com, regardless of cluster architecture.
This depends on https://github.com/openshift/oc/pull/153 to provide the new binaries in cli-artifacts.
Because this affects cluster deployment, we are looking to get this into 4.2 and later branches (we can provide separate PRs for stable branches as needed).
=> Enable multi-arch support in downloads

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go
Folks could presumably be running these OSes on other architectures.  For example, [the GOOS/GOARCH docs][1] provide for darwin on 386, amd64, arm, and arm64 and windows on 386 and amd64 (although [Windows runs on ARM64][2] and possibly other architectures as well).
I'm sticking with `x86_64` for consistency with the Linux entry from 865d84d7bb (#343).  Previous discussion starting [here][3].  CC @yselkowitz.
[1]: https://golang.org/doc/install/source#environment
[2]: https://docs.microsoft.com/en-us/windows/arm/
[3]: https://github.com/openshift/console-operator/pull/343#discussion_r347735631
=> pkg/console/controllers/clidownloads/controller: Arch qualifiers for Mac/Windows

pkg/console/starter/starter.go
Per this comment: https://github.com/openshift/console-operator/pull/355#discussion_r352743247
I'm removing the stale conditions, but leaving the controller with a comment for future use.  The potential to wedge the operator permanently inclines me strongly to keep the controller present, even if inactive for now.
/assign @spadgett @jhadvig
=> Remove stale conditions from RemoveStaleConditionsController()

manifests/07-downloads-deployment.yaml
In order for console-operator deployment to succeed, cli-artifacts needs to be available on all arches for downloads-openshift-console. However, in that case, /usr/bin/oc (inherited from cli) is a native binary, and we want to provide all primary Linux architectures to match those on mirror.openshift.com, regardless of cluster architecture.
This depends on https://github.com/openshift/oc/pull/168 to provide the new binaries in cli-artifacts for 4.2.
This is a cherry-pick of the first commit from https://github.com/openshift/console-operator/pull/343.  The other commits from that PR are relevant only to new code in 4.3+.
=> Bug 1773808: Enable multi-arch support in downloads [4.2]

hack/test-unit.sh, pkg/api/api.go, pkg/console/controllers/resourcesyncdestination/controller.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Revering and renaming the revert of the https://github.com/openshift/console-operator/pull/328 based on https://github.com/openshift/enhancements/pull/126
=> Sync default-ingress-cert to the console namespace

manifests/07-downloads-helm.yaml
This PR adds to OpenShift Console the additional Helm CLI download link(s).
=> Bug 1784582: Added Helm CLI download links

manifests/03-rbac-role-ns-openshift-config-managed.yaml, manifests/04-rbac-rolebinding.yaml, manifests/06-sa.yaml, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Adding:
- `Role` for GETting ConfigMaps from the `openshift-config-managed` namespace. Haven't found any existing Role on the cluster that would be suitable.
- `ServiceAccount` for the console, since there are only default ServiceAccounts in the `openshift-console` namespace
- `RoleBinding` - for binding the added `Role` and `ServiceAccount`
Story: https://issues.redhat.com/browse/CONSOLE-1993
=> RBAC for console backend to request openshift-config-managed configmaps

manifests/05-config.yaml, manifests/07-downloads-deployment.yaml, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/config_merger_test.go
Simpler/preferred change over #374 
RE [doc changes needed](https://docs.google.com/document/d/1zznvkK87y7UvOJZqs2DM4oWzx94P8Lg6YUb43whil3g/edit#heading=h.wp47a79o7bw0)
/assign @russellb 
/cc @spadgett @jhadvig 
- Per https://github.com/openshift-kni/console-operator/commit/31b4d3910f2d476d3351d14f0999a75c46195914
- Per https://github.com/openshift-kni/console-operator/commit/01865a640a24ee0bd719306c7a5b08802667e84d
- Per https://github.com/openshift-kni/console-operator/commit/f395cb1a571fc867046750bc57a490e1d5264f24
- all unit tests updated to verify the expected output
- All current tests should continue to pass on IPv4
- Unclear how to test an IPv6 cluster at this time
=> Bug 1794546: Console-1933: IPv6 support (simpler alternative)

manifests/05-config.yaml, manifests/07-downloads-deployment.yaml, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/config_merger_test.go
Backport of #375 
Manual cherry pick to eliminate the extra unit test for the `default-ingress-cert` as that does not exist in 4.3.
https://bugzilla.redhat.com/show_bug.cgi?id=1794548
/assign @russellb
/cc @spadgett @jhadvig
=> Bug 1794548: IPv6 support to console operator & console [openshift-4.3.z]

pkg/console/version/version.go
=> Bug 1798315: Console operator should provide valid gitCommit and gitVersion versions

pkg/api/api.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
Taking `monitoring-shared-config` and `logging-shared-config` CMs from `openshift-config-managed` namespace and feeding them to the `console-config`
(logging is missing since the [PR](https://github.com/openshift/cluster-logging-operator/pull/374) is not merged yet)
=> Bug 1777486: Add monitoring-shared-config and logging-shared-config configmaps from openshift-config-managed to the console-config

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
When a pod is marked deleted, endpoints are updated instantly and
propagate to load balancers, routers, and nodes. A component that
wishes to remain available during upgrades must wait longer than
the default propagation interval for these changes to avoid having
requests delivered to pods that are shutting down.
Change the console to wait 25s before terminating the serving
process and up to 40s on the node to ensure all front ends have
time to drain. The minimum interval here is how long an average
connection can take behind the router to drain, once new connections
stop getting created. I.e.
wait = time to propagate endpoints (5s) +
time for router reload (5s) +
time for longest request to finish (15s)
= 25s
This change should result in the console not being disrupted during
upgrade (0s …
=> Bug 1809665: The console should wait until it is out of rotation to shut down

pkg/console/subresource/consoleserver/types.go
Adding missing [types](https://github.com/openshift/console/blob/master/pkg/serverconfig/types.go#L63-L70) to have type parity with the console repo
=> Add Helm and HelmChartRepo types

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go
Will be a backport to 4.4 & 4.3.z.
=> Update oc clidownload cr to indicate that certain builds are unsupported

pkg/console/controllers/route/controller.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go
@benjaminapetersen I've finalised your work from https://github.com/openshift/console-operator/pull/350
Tested the change manually and the controller is stomping the route on edit and recreating on delete.
Although when a label or annotation is edited on the route the controller wont stomp the route, not sure if thats desirable.
=> Route controller

pkg/console/controllers/route/controller.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go
Rework of https://github.com/openshift/console-operator/pull/334
=> Status handling for RouteHealth

pkg/console/operator/sync_v400.go
Configure the console to use the `default-ingress-cert` configmap if the configmap exists, or else to use the default CA if the configmap is absent. Before this commit, the operator did exactly the reverse.
Fix a comment that falsely stated that the configmap would be absent if the administrator provided a default certificate for every ingress controller.
Follow-up to #361.
* `pkg/console/operator/sync_v400.go`: Invert the value of `useDefaultCAFile`.  Fix a comment.
----
@jhadvig
=> Fix console oauthEndpointCAFile setting

manifests/07-downloads-helm.yaml
Helm 3 becomes GA with OpenShift 4.4
=> Remove "Technology Preview" reference from Helm CLI download description

manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-console.yaml, manifests/03-rbac-role-ns-openshift-config.yaml, pkg/api/api.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/route/controller_test.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, pkg/console/subresource/route/route.go, pkg/console/subresource/route/route_test.go
Adding option do specify the custom hostname for console.
When when custom hostname is specified a new `console-custom` route is created. In case the new hostname doesnt contain the cluster domain as a suffix, secret reference needs to be specified, that points to the secret in the `openshift-config` namespace, where it needs to be created manually and contain **tls** cert and its key, which will serve as a **serving-cert** for the console pod. Also we will maintain the default route so it stays reserved for us.
API changes - https://github.com/openshift/api/pull/594
=> Custom console route

manifests/03-rbac-role-cluster.yaml, manifests/04-rbac-rolebinding-cluster.yaml
https://issues.redhat.com/browse/ODC-3398
New endpoint is being added in console backend to list knative event source CRDs. 
Ref: https://github.com/openshift/console/pull/4945. 
In order to allow an unprivileged user to get this information without read access to CRDs, new RBAC has been added here to authorise service account to list CRDs.
=> Bug 1826716: RBAC to authorise service account to list CRDs

manifests/09-console-link-openshift-learning-portal.yaml
Jan Kleinert
I'd like to append:
`?ref=webconsole`
That way we can filter for this traffic without stomping on any referral info
=> Bug 1828272: Update 'Learning Portal' console helpMenu url to track where request it is coming from

pkg/console/controllers/clidownloads/controller.go
Fixes - https://issues.redhat.com/browse/ODC-3459
Updates in this PR -
- Changes the CLI download page text odo and removes `OpenShift Do` as we are moving away from calling odo "OpenShift Do".
=> Bug 1835337: Update CLI download page text for odo

pkg/console/operator/sync_v400.go, pkg/console/status/status.go
Items:
- remove unused `getDeploymentGeneration()`
- use library-go's SetDeploymentGeneration - already done in https://github.com/openshift/console-operator/pull/424 by adding `status.UpdateDeploymentGeneration()`
- do not ignore errors when we flush status https://github.com/openshift/console-operator/pull/424#discussion_r421744310 - taken care in https://github.com/openshift/console-operator/pull/424
@benjaminapetersen not sure if other refact/cleanUp is needed at this point. We can go through it..
PTAL
=> Bug 1833465: Updating operator status - cleanUp

pkg/console/controllers/route/controller.go, pkg/console/controllers/route/controller_test.go, pkg/console/subresource/route/route.go
We should try to sync the custom route before the default one to prevent any unwanted states in which the console could become inaccessible.
Condition screen:
=> Bug 1834222: Check for custom console route hostname not to be the same as the default route

manifests/07-operator.yaml, pkg/console/controllers/route/controller.go
not sure if we should not backport to 4.4 ?
=> Bug 1835551: Inject proxy envars to console-operator deployment

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/route/controller.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/route/route.go, pkg/console/subresource/route/route_test.go, test/e2e/downloads_test.go
This basically refacts a bit the `GetCanonicalHost` function and adds unit test for it.
=> Bug 1835221: Sync loop should error out on resources that depend on route that is not admitted

manifests/03-rbac-role-cluster.yaml
This PR grants Console SA permissions to read webhooks configurations to check if the terminal operator is correctly installed.
It's needed for https://github.com/openshift/console/pull/5332
Now we try to figure out what is the right way to detect operator installed, like check deployment in openshift-operators, or ClusterServiceVersion, ... So, probably permissions list here will be extended
=> Bug 1839621: Grant Console SA permissions to read webhooks configurations

manifests/07-downloads-deployment.yaml
* Version: OCP4.4+
* Description:
When IPv6 is disabled, the socket binding will be failed, so we catch the exception and then IPv4 would use at that time.
* Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1846922
=> Bug 1846922: "downloads" pod does not work on the node which is disabled IPv6

pkg/console/operator/sync_v400.go
We should be updating the console config status only when the consoleURL change
=> Bug 1853270: Update console config on change

manifests/03-rbac-role-cluster.yaml, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
We fetch the inactivity timeout first from the `accessTokenInactivityTimeoutSeconds` in the `OAuthClient`. If thats not set we fetch `accessTokenInactivityTimeout` field from `OAuth` config. The inactivity timeout is stored in seconds.
When the inactivity timeout is set, the console configmap will look:
```yaml
apiVersion: console.openshift.io/v1
auth:
clientID: console
clientSecretFile: /var/oauth-config/clientSecret
inactivityTimeoutSeconds: 600
oauthEndpointCAFile: /var/default-ingress-cert/ca-bundle.crt
clusterInfo:
consoleBaseAddress: https://console-openshift-console.cluster.openshift.com
masterPublicURL: https://api.cluster.openshift.com:6443
customization:
branding: ocp
documentationBaseURL: https://docs.openshift.com/container-platform/4.5/
kind: ConsoleConfig
monitoringInfo: …
```
=> Implement inactivity timeout for logging user out

manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-openshift-config.yaml, manifests/04-rbac-rolebinding.yaml
This change allows non-admin users logged through UI to browse helm charts
available in custom configured Helm chart repositories.
A separate PR will be submited to openshift/console making /api/helm/charts/index.yaml
to perform k8s api requests on behalf of the service account.
=> Allow console service account to read HelmChartRepository CR

manifests/07-downloads-deployment.yaml
Conservative, filesystem-based web servers [should][1] [avoid][2] dynamic directory listing, to avoid accidentally leaking a file that a user drops into the served filesystem.  It seems like an unlikely vector for the downloads container, where nobody outside of our script is likely to be dropping files.  But it is easy enough to fix by filling in `index.html` files throughout, which preempt `SimpleHTTPRequestHandler`'s [directory][3] [listing][4].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1859331
[2]: https://cwe.mitre.org/data/definitions/548.html
[3]: https://docs.python.org/2.7/library/simplehttpserver.html#SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET
[4]: https://github.com/python/cpython/blob/e7c98f08e228e9f6e139d61e3e5d0a5018a38f0b/Lib/http/server.py#L757-L758
=> Bug 1859331: manifests/07-downloads-deployment: Create index.html

manifests/07-downloads-deployment.yaml
The variable root is left over from the previous for loop, it shouldn't
be used again here.
/assign @wking
=> Bug 1859331: Fix downloads index

pkg/console/controllers/route/controller.go, pkg/console/subresource/route/route.go, pkg/console/subresource/route/route_test.go
When cluster user wants to define custom TLS secret for the default route he should just define the secret's name in the console-operator config. The issue is that we cannot have two routes(default, custom) with the same hostname.
I thing we should update the API [comment](https://github.com/openshift/api/blob/master/operator/v1/types_console.go#L51-L59) with this use-case.
Also we should probably backport this fix to 4.5
=> Bug 1870514: Configuring custom certificate for default console route

manifests/01-helm.yaml, manifests/03-rbac-role-cluster.yaml, manifests/04-rbac-rolebinding-cluster.yaml
Although console endpoint `/api/helm/charts/index.yaml` handles the situation
when there is no HelmChartRepository CR present in the cluster, we should align
us to other default cluster settings and provide the default HelmChartRepository CR in the payload
Prior introducing openshift/console#5933 all authenticated users could browse the charts from the chart repo.
This PR restores that functionality by introducing additional `helm-chartrepos-viewer` ClusterRole,
binding it to all authenticated users.
=> Bug 1872375: Add RedHat Helm chart repository as default repo in OCP payload

manifests/07-downloads-deployment.yaml, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go
Putting this into queue until https://github.com/openshift/console-operator/pull/440 is in.
=> [release-4.4] Bug 1847323: Publish license file

vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml, vendor/github.com/openshift/api/config/v1/types_oauth.go, vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go, vendor/modules.txt
Need to fix this inconsistency due to the failures https://github.com/openshift/release/pull/12006
```
2020/09/18 14:52:20 Executing test unit
go test  -race ./pkg/... ./cmd/...
go: inconsistent vendoring in /go/src/github.com/openshift/console-operator:
github.com/openshift/api@v0.0.0-20200429152225-b98a784d8e6d: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/openshift/api@v0.0.0-20200424083944-0422dc17083e
github.com/openshift/client-go@v0.0.0-20200422192633-6f6c07fc2a70: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/openshift/client-go@v0.0.0-20200326155132-2a6cd50aedd0
```
=> Bug 1880307: Fix inconsistent vendoring in vendor/modules.txt

Dockerfile.rhel7
Updating openshift-enterprise-console-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-console-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating openshift-enterprise-console-operator builder & base images to be consistent with ART

pkg/console/subresource/deployment/deployment.go
This changes the capnslog values to accepted klog log level values.  I have just converted them as best I can but we might want to re-evaluate what each maps to.
[CONSOLE-1523](https://issues.redhat.com/browse/CONSOLE-1523)
=> CONSOLE-1523: Change log level values to use klog types

pkg/console/subresource/configmap/brand_ocp.go
Bump DEFAULT_DOC_URL for 4.7 then documentationBaseURL will point to correct link https://docs.openshift.com/container-platform/4.7/
=> Bug 1896645: Bump DEFAULT_DOC_URL for ocp 4.7

manifests/02-namespace.yaml, manifests/03-rbac-role-ns-openshift-console-user-settings.yaml
**Fixes**: 
https://issues.redhat.com/browse/ODC-4755
**Analysis / Root cause**:
Based on the [User Settings for OpenShift Console enhancement proposal](https://github.com/openshift/enhancements/blob/master/enhancements/console/user-settings.md) we want to create a `ConfigMap` for each individual user in the namespace `openshift-console-user-settings`
We create a `ConfigMap` with a service account from the console bridge, see PR https://github.com/openshift/console/pull/7095. For this we need that the namespace, role and rolebinding which is added in this PR.
**Solution Description**: 
* Add Namespace `openshift-console-user-settings`
* Add Role and RoleBinding `console-user-settings-role-operator` to allow the ServiceAccount to get, list, create, update and delete Role, RoleBinding and …
=> Add namespace and role resources for user settings

manifests/03-rbac-role-ns-openshift-console-user-settings.yaml
**Fixes**: 
https://issues.redhat.com/browse/ODC-4755
**Analysis / Root cause**:
Get an forbidden error on a shared cluster with new user settings api.
**Solution Description**: 
* Removed version suffix of Role `rules.apiGroups to fix
`Failed to create user settings: roles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:openshift-console:console" cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "openshift-console-user-settings"`
* Fixed typo in verbs, we have two times watch instead of watch and patch. Doh! :facepalm: 
`Failed to create user settings: roles.rbac.authorization.k8s.io "user-settings-kubeadmin-role" is forbidden: user "system:serviceaccount:openshift-console:console" (groups=["system:serviceaccounts" …
=> Fix user settings role definition for console service account

manifests/0000_90_console-operator_01_prometheusrbac.yaml, manifests/0000_90_console-operator_02_servicemonitor.yaml, manifests/01-helm.yaml, manifests/01-oauth.yaml, manifests/01-operator-config.yaml, manifests/02-namespace.yaml, manifests/03-rbac-role-cluster-extensions.yaml, manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-console.yaml, manifests/03-rbac-role-ns-openshift-config-managed.yaml, manifests/03-rbac-role-ns-openshift-config.yaml, manifests/03-rbac-role-ns-openshift-console-user-settings.yaml, manifests/03-rbac-role-ns-operator.yaml, manifests/04-rbac-rolebinding-cluster.yaml, manifests/04-rbac-rolebinding.yaml, manifests/05-config-public.yaml, manifests/05-config.yaml, manifests/05-service.yaml, manifests/06-sa.yaml, manifests/07-downloads-deployment.yaml, manifests/07-downloads-helm.yaml, manifests/07-downloads-route.yaml, manifests/07-downloads-service.yaml, manifests/07-operator.yaml, manifests/08-clusteroperator.yaml, manifests/09-console-link-openshift-blog.yaml, manifests/09-console-link-openshift-learning-portal.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all console-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
=> Annotate manifests for single-node-developer cluster profile

Dockerfile.rhel7, README.md, quickstarts/README.md, quickstarts/add-healthchecks-quickstart.yaml, quickstarts/explore-pipeline-quickstart.yaml, quickstarts/explore-serverless-quickstart.yaml, quickstarts/monitor-sampleapp-quickstart.yaml, quickstarts/sample-application-quickstart.yaml
This PR contributes the initial out-of-the-box quick start custom resources and adds a brief README discussing the contribution process.
[CONSOLE-2472](https://issues.redhat.com/browse/CONSOLE-2472)
=> CONSOLE-2472: Add initial quick starts

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
**Fixes**: 
https://issues.redhat.com/browse/ODC-5238
https://bugzilla.redhat.com/show_bug.cgi?id=1906798
**Analysis / Root cause**:
With the changes in https://github.com/openshift/api/pull/763, https://github.com/openshift/console-operator/pull/484 and https://github.com/openshift/console/pull/7196 we prepared that the developer catalog categories could be customized by the admin.
But changes to the Console (operator.openshift.io/v1) resource "cluster"  was not transferred to the ConfigMap "console-config" (in namespace "openshift-console") data entry `console-config.yaml`. This config entry was used as mounted console-config.yaml when starting a bridge.
**Solution Description**: 
The Console "cluster" customization data was not copied 1:1 to the ConfigMap "console-config". So it was …
=> Bug 1906798: Export operator dev catalog customization to console-config ConfigMap

manifests/03-rbac-role-cluster-extensions.yaml
=> Bug 1906713: Logged user should be able to get consolequickstarts

quickstarts/ocs-install-tour-quickstart.yaml
Depends on https://github.com/openshift/console-operator/pull/490
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
=> Bug 1907280: Adds quickstart for ocs install tour

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Based on the bug description, we should avoid several minute outage in case of node failure pods are rescheduled to a healthy zone. For that reason we should use `RequiredDuringSchedulingIgnoredDuringExecution`, due to the [docs](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#tolerating-node-failure).
Also 3 console replicas are recommended, although not sure if that's necessary.
=> Bug 1894216: Improve OpenShift Console availability

pkg/console/operator/sync_v400.go, test/e2e/plugins_test.go
When we fail to fetch any of the set plugins in the console-operator config, dont set an endpoint for it and just skip it.
If the plugins will be created additionally, informer will trigger a next sync loop.
also update e2e test for adding available and unavailable plugin names to the console-operator config
=> Bug 1917759: Dont panic after setting plugin that does not exists to the console-operator config

quickstarts/manage-helm-repos.yaml, quickstarts/node-with-s2i.yaml, quickstarts/quarkus-with-helm.yaml, quickstarts/quarkus-with-s2i.yaml, quickstarts/spring-with-s2i.yaml
Adding five (5) new Quick Starts for 4.7, which focus on the developer experience.
4 of these are available for all users:
- Get started with Node
- Get started with Quarkus with a Helm Chart
- Get started with Quarkus with s2i
- Get started with Spring Boot
1 needs special permissions:
- Manage available content in the Helm Chart Catalog
Note: Each of these have specific icons
I've attached a screenshot of Quick Starts page with them all installed:
Link to videos:
- [Get started with Node](https://drive.google.com/file/d/1FqQHc1yBVdi9inxHm0zfd2-BrHOUnQGb/view?usp=sharing) 
- [Get started with Quarkus using a Helm Chart](https://drive.google.com/file/d/1mhNAxlSSeqDaJWo941lyH3BDjEHJuFKi/view?usp=sharing)
- [Get started with Quarkus with …
=> New 4.7 Quick Starts focusing on the developer experience

test/e2e/framework/framework.go
Due to the small polling interval the `RemovedTest` has been flaking, since we didnt get all the operator sync loop enough between testing if all the resources are removed and not recreated.
=> Bump polling interval when checking for resource unavailability

pkg/console/subresource/configmap/configmap.go
=> Bug 1935541: Check for error when generating default and user-defined config for the console-config configmap

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, test/e2e/deployment_replicas_test.go, test/e2e/framework/clientset.go, test/e2e/framework/framework.go, test/e2e/plugins_test.go
adding e2e test to check the `console` && `downloads` deployments replicas, based on the Infrastructure config, since the release team will by adding and enabling single-node cluster prow job to this repo.
=> Add e2e test to check correct deployment replicas, based on the Infrastructure config TopologyMode

manifests/03-rbac-role-cluster.yaml
This PR adds in additional permissions that are needed for https://github.com/openshift/console/pull/8342. We are using it to check if the web-terminal operator is installed on the cluster.
Related issue: https://issues.redhat.com/browse/WTO-20
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
=> Add in get subscriptions to console service account

Makefile, go.mod, go.sum, manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml, profile-patches/ibm-cloud-managed/07-operator.yaml-patch, vendor/github.com/openshift/build-machinery-go/OWNERS, vendor/github.com/openshift/build-machinery-go/README.md, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk, vendor/modules.txt
Bumps build-machinery-go to latest
Adds patch specific to ibm-cloud-managed profile that generates a manifest that removes node selector for operator deployment
`make verify` verifies that the generated manifest is up to date
`make update` updates the manifest by applying the ibm-cloud-managed patch to the original deployment manifest
=> IBM Cloud manifest profile patch

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
Issue: https://issues.redhat.com/browse/ODC-5447
Add project access customization details to console-config ConfigMap.
Based on enhancement proposal https://github.com/openshift/enhancements/pull/668
Depends on https://github.com/openshift/console-operator/pull/519 to get update from https://github.com/openshift/api/pull/857
=> Export project access details to console-config ConfigMap

pkg/console/operator/operator.go
Removing the `ResyncEvery()` method from the operator sync loop. The issue is that the operator sync loop is syncing multiple resources, not just the deployment, which was causing re-deployment. For that reason we cant resync periodically this controller.
The periodical redepoyment was causing also panic in the `k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1` 
```
2021-04-09T15:31:25.666699821Z I0409 15:31:25.666622       1 event.go:282] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-console-operator", Name:"console-operator", UID:"efb36fcc-940d-4563-a9bc-54c14ea1ac29", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeploymentUpdated' Updated Deployment.apps/downloads -n openshift-console because it changed …
```
=> Bug 1948524: Remove ResyncEvery method from the operator sync loop

manifests/02-namespace.yaml, manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Add management workload annotations

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
fixes: https://issues.redhat.com/browse/ODC-5566
Export Quick start disabled data to console config map
Based on the enhancement proposal https://github.com/openshift/enhancements/pull/715
=> Export quickStarts data to console-config ConfigMap

pkg/cmd/operator/cmd.go
Update to non-deprecated cmd method with TODO context.
```go
// NewCommand returns a new command that a caller must set the Use and Descriptions on.  It wires default log, profiling,
// leader election and other "normal" behaviors.
// Deprecated: Use the NewCommandWithContext instead, this is here to be less disturbing for existing usages.
func (c *ControllerCommandConfig) NewCommand() *cobra.Command {
return c.NewCommandWithContext(context.TODO())
}
```
=> update to non-deprecated NewCommand method

manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml, pkg/console/subresource/deployment/deployment.go
As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged
=> Rename workload annotations

quickstarts/manage-helm-repos.yaml
=> Bug 1956610: Add missing cluster profile annotations to manage-helm-repos quickstart manifest

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/downloadsdeployment/controller.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/service/controller.go, pkg/console/operator/operator.go, pkg/console/starter/starter.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Remove the `ResyncEvery(time.Minute)` from most of the controllers, so unnecessary sync loops are not triggered. Instead I've created a `HealthCheckController` that should contain all the health check that we have (currently only for `console` route), and will add in the future. This controller sync is triggered periodically, every minute.
=> Bug 1948524: Update operator's status with downloads deployment generation && pull route health check into a standalone controller

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
This PR will add the priority class field to the downloads subresource.
Based on the descriptions Ravi put in the BZ, choosing to use
"system-cluster-critical" value for the default deployment. Updated
and de-duplicated unit tests.
https://bugzilla.redhat.com/show_bug.cgi?id=1954866
=> Bug 1954866: Add necessary priority class to downloads

manifests/03-rbac-role-ns-openshift-config-managed.yaml, pkg/console/operator/sync_v400.go
console-operator doesnt have RBAc to create `console-public` CM in the `openshift-config-managed` NS, thats why we had it in the `/manifest` folder, so CVO would create it.
Just FYI, sin the `resourceapply.ApplyConfigMap()` is merging labels and annotations we dont need to have the `release.openshift.io` have in the bindata of the `console-public` CM. 
/assigne @spadgett 
@florkbr fyi
=> Bug 1962698: Console-operator can not create resource console-public configmap in the openshift-config-managed namespace

manifests/01-helm.yaml
All OpenShift charts will come from the repo with OpenShift
certified charts. All the charts in the current repo will go
through the certification program https://charts.openshift.io
=> Switching the URL of the default openshift helm repo.

pkg/console/controllers/healthcheck/controller.go
We haven't been reporting `Available: False` when the console route was not accessible.
=> Bug 1952405: Console operator should report Available:False when it's route is not accessible

manifests/02-namespace.yaml
Adding the `network.openshift.io/policy-group` label based.
@sleshchenko FYI
=> Bug 1975714: Add policy-group label to the openshift-console namespace manifest

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/downloadsdeployment/controller.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/service/controller.go, pkg/console/starter/starter.go, pkg/console/subresource/route/route.go
Removing all the unnecessary resourceSyncer instances passed to operator's controllers.
Originally this refactoring PR should be bigger, but since we are too close to release I've decide to address other naming and structural changes in 4.9
/assign @spadgett @florkbr
=> Bug 1966480: Console-operator's controllers are passed resourceSyncer which is not used

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Use `requiredDuringSchedulingIgnoredDuringExecution` for anti-affinity rules on both console's deployments.
The label selectors for console deployment will be:
`"app": "console", "component": "ui"`
The label selectors for downloads deployment will be:
`"app": "console", "component": "downloads"`
=> Bug 1975379: Use hard requirement for anti-affinity rules on both console's deployments

quickstarts/node-with-s2i.yaml
This updates the example repo for the Node.js quickstart.  The current repo has been archived and moved.  This PR points to the correct repo that we, the nodeshift, are still maintaining
=> fix: Update the Node.js quickstart example repo.

quickstarts/monitor-sampleapp-quickstart.yaml
**Fixes:**
https://issues.redhat.com/browse/ODC-6088
**Description:**
This PR Rename `Monitoring` tab to `Observe` tab in monitoring sampleapp quickstart.
=> Rename Monitoring tab to Observe tab in monitoring sampleapp quickstart

pkg/api/api.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
This is related to [CMO-#1223](https://github.com/openshift/cluster-monitoring-operator/pull/1223) and [Console-#9276](https://github.com/openshift/console/pull/9276)
See the following epic for context https://issues.redhat.com/browse/MON-1591
cc @simonpasquier, @kyoto - obviously I'm not too familiar with the console repo's but I've gone through it and cannot see any other touch points. Any suggestions on the best way to test these three PR's e2e?
=> Remove references to upstream UI components and config

quickstarts/install-odf.yaml, quickstarts/ocs-install-tour-quickstart.yaml
For 4.9 release, OCS operator will be replaced with the ODF at a higher level. Hence we would want to make sure that new install quickstart accurately represent the workflows for ODF operator.
This commit adds quickstart for installing the ODF operator and setting up the storage cluster.
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>
=> Adds ODF install tour

README.md
Reduce the directory creating by using `go get` to setup environment.
I noticed that when I build I get the `console` binary directly in my working directory and not in an `_output` directory.  I didn't update that because I wasn't sure if that was correct or not.  Example below.  Let me know if that needs updating too or if my environment is bad.  
```
[vagrant@localhost console-operator]$ echo $GOPATH
/home/vagrant/codebase/console-operator
[vagrant@localhost console-operator]$ pwd
/home/vagrant/codebase/console-operator/src/github.com/openshift/console-operator
[vagrant@localhost console-operator]$ make clean && make
rm -f console
rm -f '_output/tools/bin/yq'
if [ -d '_output/tools/bin/' ]; then rmdir --ignore-fail-on-non-empty -p '_output/tools/bin/'; fi
rm -f …
```
=> reduce initial steps to setup project

quickstarts/ocs-install-tour-quickstart.yaml
Fixes: https://issues.redhat.com/browse/ODC-6241 ( relates to  https://issues.redhat.com/browse/ODC-6161 )
Added the described accessReviewResources inside OCS quickstart -spec
since this quick start should only be available if you can install operators
I am seeing the operator install option in `KUBEADMIN` login
but not seeing the quickstart, is this expected from the given `accessReviewResources:`
=> Bug 2000440: OCS Quick Start should not be shown unless you have proper privileges

pkg/api/api.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/route/controller.go, pkg/console/starter/starter.go
How route health check we need to use `DefaultIngressCert` not the `OAuthServingCertConfigMapName`.
This is related to failing health checks in the https://bugzilla.redhat.com/show_bug.cgi?id=1989055#c7
Also removing dead code from route controller.
/assign @stlaz @spadgett 
@florkbr FYI
=> Bug 1989055: Revoke usage of Default Ingress Cert for console route healthcheck

pkg/console/operator/sync_v400.go, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
When setting console-operator Available condition it should be enough to check if there is at least one available replica.
=> Bug 1994443: console-operator should report Available=true when at least available replica exists

pkg/console/subresource/deployment/deployment.go
This fix will set the `server` value to `""` since otherwise we would need to override the whole SimpleHTTP module. That would be an overkill due to that fact that we are inlining the server code in the containers spec.
response will look:
@rludva FYI
=> Bug 2001240: Remove SimpleHTTP 'server' response header value

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/downloadsdeployment/controller.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/service/controller.go, pkg/console/operator/operator.go
Resync of the controllers was removed in https://github.com/openshift/console-operator/pull/531. But since it looks like we need it Im adding them back.
Together with https://github.com/openshift/console-operator/pull/580 PR this issue should be solved. Wondering if a minute is the right period here.
@TheRealJon @florkbr FIY
=> Bug 1999314: Resync all controllers periodically

go.mod
=> Bug 2008185: Console operator go.mod should use go 1.16 version

pkg/console/subresource/configmap/brand_ocp.go, quickstarts/add-healthchecks-quickstart.yaml, quickstarts/explore-pipeline-quickstart.yaml, quickstarts/install-serverless.yaml
In line with efforts currently under way for OCM, we need to update and migrate all docs.openshift.com links to access.redhat.com.
This needs to be considered in tandem with https://github.com/openshift/console/pull/10354
/assign @spadgett﻿
=> Bug 2018380: Migrate docs links to access.redhat.com

quickstarts/install-odf.yaml
This is a backport of https://github.com/openshift/console-operator/pull/598 and also incorporates the follow up correction added in https://github.com/openshift/console-operator/pull/608
Note: We had an automated cherry-pick https://github.com/openshift/console-operator/pull/604, but, it do not have follow up correction which is added in https://github.com/openshift/console-operator/pull/608. Thus, this new PR.
=> [release-4.9] Bug 2016028: Correction/Changes in Quick Start Guides for ODF

manifests/07-downloads-deployment.yaml, pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
Manual backport of https://github.com/openshift/console-operator/pull/589, stripped of single node cluster work.
=> Bug 2016654: Use hard requirements for antiaffinity rules

manifests/03-rbac-role-cluster.yaml
This PR cherry-picks https://github.com/openshift/console-operator/pull/588 back to 4.9. Related Console side PR backport for 4.9 is: https://github.com/openshift/console/pull/10135
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
(cherry picked from commit 84d500a1822961ba406736bca02864a7caffb9a6)
=> [release-4.9] Bug 2008142: Change web terminal subscription permissions from get to list

pkg/console/controllers/clidownloads/controller.go
Fixes - https://github.com/openshift/console/issues/10415
Updates in this PR -
- Changes the CLI download link for odo to latest developer mirror - https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest.
=> Bug 2036937: Update download odo link to new mirror

bindata/deployments/downloads-deployment.yaml, pkg/console/assets/bindata.go, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go
A darwin/arm64 oc binary was added to cli-artifacts in https://github.com/openshift/oc/pull/990 .﻿
=> Bug 2033434: clidownloads: add darwin/arm64 oc

pkg/console/controllers/route/controller.go, pkg/console/subresource/route/route.go, test/e2e/custom_url_test.go
Issue was with setting an ingress's `componentRoute` only with TLS secret(not supplying hostname), which should be set for default route. Fixing the issue and adding two e2e tests.
/assign @TheRealJon @spadgett
=> Bug 2037635: Fix setting of custom cert for default route

quickstarts/install-helmchartrepo-ns.yaml
Adding a Quick Start for installing namespaced Helm Chart Repos.  This Quick Start will be linked to from the description of the Helm Chart Catalog.  Please see screenshots below:
Quick Start Card:
Quick Start Overview:
Quick Start Step:
Quick Start Verify:
Quick Start Conclusion:
=> Add QS for installing namespeced Helm Chart Repos

manifests/03-rbac-role-cluster.yaml
This PR cherry-picks https://github.com/openshift/console-operator/pull/588 back to 4.8. Related Console side PR backport for 4.8 is: https://github.com/openshift/console/pull/10134
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
(cherry picked from commit 84d500a1822961ba406736bca02864a7caffb9a6)
=> [release-4.8] Bug 2008141: Change web terminal subscription permissions from get to list

Dockerfile.rhel7
This change is needed to initialize and vendor the newly add Helm CRD. Currently, the API schema has been merged but has not been initialized in our cluster yet.
Refer: https://github.com/openshift/api/pull/1084
Signed-off-by: Allen Bai <carpe.diem.allen@gmail.com>
=> Dockerfile.rhel7: add new Helm CRD, ProjectHelmChartRepository

quickstarts/install-odf.yaml
**Fixes:**
https://issues.redhat.com/browse/ODC-6161
**Root analysis:**
access review resources were not added to the quick start
**Solution description:**
added access review resources
**GIF/Screenshot:**
=> Bug 2048541: ODF quickstart permissions check

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
Infrastructure config's `ControlPlaneToplogy` will be stored in the console-config.yaml under `clusterInfo.controlPlaneTopology`.
/assign @zherman0
=> CONSOLE 3070: Console-operator should pass infrastructure config's ControlPlaneToplogy to the console-config.yaml

pkg/console/operator/operator.go, pkg/console/status/status.go
We havent been setting the right conditions when the console-operator has been set to `Removed` state. The correct ones should be `Available: True` & `Degraded: False`, when no error occurs during the removal process. 
=> Bug 2057696: Console operator should not block installation/upgrade process when set to Removed state

quickstarts/explore-pipeline-quickstart.yaml
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2067155
Description:
Quickstart installation step contains outdated operator name, so users following that step will not be able to find the operator by following the steps.
Solution:
Updated the content with latest operator name.
`Openshift Pipelines Operator` is changed to `Red Hat Openshift Pipelines`
cc: @serenamarie125
=> Bug 2067155: Modify the operator display name to match it with the name displayed in operatorhub

bindata/deployments/console-deployment.yaml, bindata/deployments/downloads-deployment.yaml, go.mod, manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml, pkg/console/assets/bindata.go, pkg/console/subresource/deployment/deployment_test.go, vendor/modules.txt
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
"objectRef": "openshift-console-operator/pods/",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": runAsNonRoot != true (pod or container \"console-operator\" must set securityContext.runAsNonRoot=true)"
}
```
/cc @stlaz
=> Bug 2086519: AUTH-133: manifests: comply to restricted pod security

.gitignore, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
**Implements**: 
https://issues.redhat.com/browse/ODC-6670
:arrow_right: [Full Epic implementation documentation](https://docs.google.com/document/d/1PgQvB1TKwRH9Peezbr7Fu-raj-zU4iDFK9SJ6bZqxhs/edit)
To configure the new (separate PR in [openshift/console](https://github.com/openshift/console)) `telemetry-plugin` we need a generic mechanism to configure this plugin.
This PR automatically applies `telemetry.console.openshift.io/` prefixed annotations of the `operator.openshift.io/Console` `cluster` resource [1] to the `console-config.yaml` [2].
Add some prefixed annotations to `operator.openshift.io/Console` `cluster` resource [1]:
```yaml
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
annotations:
telemetry.console.openshift.io/A_CONFIG_KEY: value1 …
```
=> ODC-6670: Sync consoleConfig telemetry annotations to console-config.yaml

pkg/api/api.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go, test/e2e/plugins_test.go
console-operator should be checking for the new `console.openshift.io/default-i18next-namespace` annotation, update the `console-config.yaml` accordingly and redeploy the console server.
For that I've refact the internal consoleserver API.
/assign @spadgett @TheRealJon 
Story: https://issues.redhat.com/browse/CONSOLE-3162
=> CONSOLE-3162: Implement check for the new i18n annotation for dynamic plugins

pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
We should be passing the RELEASE_VERSION envar into the console so we can then use is for [implementing dynamic plugin dependency resolution](https://github.com/openshift/console/pull/11626).
To achieve this we could:
1. Pass the RELEASE_VERSION envar into the console pod, so we so console backend can read it as a envar
2. We could be publishing the RELEASE_VERSION var into the console-config.yaml so the console server will read the variable and add it to `SERVER_FLAGS`. 
Based on [slack conversation](https://coreos.slack.com/archives/C011BL0FEKZ/p1653600473874119?thread_ts=1653599045.025239&cid=C011BL0FEKZ)
/assign @TheRealJon 
@vojtechszocs @spadgett FYI
=> Bug 2021297: Pass RELEASE_VERSION envar into the console pod

pkg/console/subresource/deployment/deployment.go
This PR fixes bug described in the issue https://github.com/openshift/console-operator/issues/656
=> Bug 2093852: InfrastructureTopology must be driving console affinity rule creation

pkg/console/controllers/route/controller.go
Since the `RouteController` is used for `console` and `downloads` routes so we need to distinguish between there two routes and their conditions.
/assign @stlaz
=> Bug 2055494: Distinguish between route conditions

pkg/console/controllers/downloadsdeployment/controller.go
When the console-operator is in `Removed` state and the cluster is getting upgraded, the `ConsoleDownloadsDeploymentSyncController` is failing since it's trying to remove the deployment thats already gone. We should not error out.
```
2022-05-24T14:25:14.277200211Z E0524 14:25:14.277137       1 base_controller.go:272] ConsoleDownloadsDeploymentSyncController reconciliation failed: deployments.apps "downloads" not found
2022-05-24T14:25:24.526363410Z E0524 14:25:24.526308       1 base_controller.go:272] ConsoleDownloadsDeploymentSyncController reconciliation failed: deployments.apps "downloads" not found
2022-05-24T14:25:43.091148770Z I0524 14:25:43.090952       1 operator.go:257] deleting console resources
2022-05-24T14:25:43.116870499Z I0524 14:25:43.116796       1 operator.go:286] …
```
=> Bug 2089950: Deleting downloads deployment should not fail if already deleted

manifests/03-rbac-role-cluster.yaml
This PR updates the permission change for Project Helm Chart Repository . The PR aims to aggregate the admin and edit cluster role with ability to perform actions on ProjectHelmChartRepository.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>
=> Bug 2117142: Update permission for projecthelmchartrepositories with an aggregator role

manifests/03-rbac-role-cluster.yaml
This PR updates the annotations which support the cluster role project-helm-chartrepository-editor to be created. This PR is in addition to https://github.com/openshift/console-operator/pull/667 , as the cluster role is not getting created by the operator.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>
=> Bug 2117142:update annotations for project-helm-chartrepository-editor

manifests/03-rbac-role-cluster.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
Implementing https://issues.redhat.com/browse/CONSOLE-3242
Implement logic in the console-operator that will scan though all the nodes and build a set of all the architecture types that the cluster nodes run on and pass it to the `console-config.yaml`
=> CONSOLE-3242: Heterogeneous architecture clusters

pkg/api/api.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/types.go
https://issues.redhat.com/browse/MON-2289
Requires https://github.com/openshift/cluster-monitoring-operator/pull/1690
Required by https://github.com/openshift/console/pull/11712
=> Bug 2100860: Retrieve user-defined  Alertmanager services from shared configmap

pkg/console/subresource/configmap/brand_ocp.go
Fixes: https://issues.redhat.com/browse/OCPBUGS-785
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>
=> OCPBUGS-785: Bump documentationBaseURL to 4.12

pkg/api/api.go, pkg/cmd/crdconversionwebhook/converter/converter.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, test/e2e/framework/clientset.go, test/e2e/plugins_test.go
This is an additional PR for https://issues.redhat.com/browse/CONSOLE-3069 to swap api towards the new `v1` version of ConsolePlugin CRD.
Updated packages and also tests.
=> CONSOLE-3069: Handle new v1 ConsolePlugin api in the operator

pkg/api/api.go, pkg/console/controllers/managedclusters/controller.go, pkg/console/controllers/managedclusters/controller_test.go, pkg/console/controllers/util/util.go
Add ability to remove clusters from cluster list based on several criteria:
1) ~~Remove all products with *KS values:  "AKS", "EKS", "IKS", "ROKS".  Instead of using regexp of *KS, a list was made based on product name so non-KS values can be added in the future~~
UPDATE: ROKS is allowed.  Switching logic to an allow list of: OpenShift, ROSA, ARO, ROKS, and OpenShiftDedicated
2) Remove all ocp versions less than 4.0
3) This solution does not offer the option of having the console show things as disable, instead, it works with existing filters and only includes managed clusters that pass the criteria.  To get more options on the dropdown, we probably would need to pass the entire set of managedClusters to console and then filter on the frontend side.
=> CONSOLE-3125: Add cluster filtering by product and ocp version

manifests/03-rbac-role-cluster.yaml, manifests/04-rbac-rolebinding-cluster.yaml
This was added in https://github.com/openshift/cluster-version-operator/pull/821 to allow more featuresets and allow for a future migration to include actual gates. Because usage of this manifest would prevent upgrades, there are not upgrade concerns for this change.
=> update to release.openshift.io/feature-set to match OCP 4.12 

pkg/cmd/crdconversionwebhook/converter/converter.go, pkg/cmd/crdconversionwebhook/converter/converter_test.go, pkg/console/subresource/configmap/configmap_test.go
We should be using an array entry reference rather then a memory address, while casting the object into a variable.
Also adding couple of unit tests to back case where there are multiple proxy services defined in a single plugin.
=> CONSOLE-3337: Dynamic plugin proxy reference issue

manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-operator.yaml, pkg/api/api.go, pkg/console/controllers/upgradenotification/controller.go, pkg/console/starter/starter.go
This story creates a ConsoleNotification if the cluster is under upgrade process. Once the upgrade is done we remove the notification.
Screen:
Story: https://issues.redhat.com/browse/CONSOLE-3252
=> CONSOLE-3252: Create a ConsoleNotification when cluster is performing an upgrade

manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-operator.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
Console-Operator: Set disabledCopiedCSVs for console using console config
Also added RBAC commands so we can access the OLM config file
https://issues.redhat.com/browse/CONSOLE-3286
=> CONSOLE-3286: Set disabledCopiedCSVs in console

pkg/console/controllers/upgradenotification/controller.go
Before:
After:
/cherry-pick release-4.12
=> OCPBUGS-3109: Change text colour for ConsoleNotification that notifies user that the cluster is being

pkg/console/subresource/configmap/managed_clusters.go
Ensure main console sync loop is re-run when managed-cluster config changes
=> OCPBUGS-4008: Add `app: console` label to managed-clusters configmap

quickstarts/host-inventory-quickstart.yaml, quickstarts/install-multicluster-engine.yaml
…4.12.z (#730)
* Create install-multicluster-engine.yaml
Signed-off-by: Maggie Chen <magchen@redhat.com>
* [ACM-2360](https://issues.redhat.com//browse/ACM-2360): Add more steps to host inventory quick start (#703)
* Add more steps to host inventory quick start
Signed-off-by: Maggie Chen <magchen@redhat.com>
* fix texts
Signed-off-by: Maggie Chen <magchen@redhat.com>
* fix 2 issues
Signed-off-by: Maggie Chen <magchen@redhat.com>
Signed-off-by: Maggie Chen <magchen@redhat.com>
* [ACM-2781](https://issues.redhat.com//browse/ACM-2781): Have operator as a prerequisite
Signed-off-by: Maggie Chen <magchen@redhat.com>
* refactor the line
Signed-off-by: Maggie Chen <magchen@redhat.com>
---------
Signed-off-by: Maggie Chen <magchen@redhat.com>
Co-authored-by: Joachim Schuler …
=> OCPBUGS-5499: Back port on-premise host inventory quick start to OCP 4.11.x

bindata/deployments/downloads-deployment.yaml, pkg/console/assets/bindata.go
`os.path.basename()` did not remove windows executable extension `.exe`, was replaced by `os.path.basename(os.path.splitext(path)[0])` which first splits the path, takes the part before `.` and then passes it to the original `basename()` function.
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>
=> OCPBUGS-5836: Incorrect redirection when user try to download windows oc binary

pkg/console/controllers/route/controller.go, pkg/console/starter/starter.go
This issue was introduce by https://github.com/openshift/console-operator/pull/638/files where we only delivered the fix into the 4.9 release and when upgrading to 4.10 the new conditions havent been cleaned out by the `staleConditionsController`.
Due to that issue we will need to backport to release-4.10
/assign @TheRealJon @stlaz 
ccing @palonsoro
=> OCPBUGS-2783: Distinguish between route conditions and remove the old ones

manifests/cluster-monitoring-prometheus-rules.yaml
Fixes: [ODC-7303](https://issues.redhat.com/browse/ODC-7303)
This PR adds a new PrometheusRule to the console-operator for the data collected in [ODC-7232](https://issues.redhat.com/browse/ODC-7232).
This queries are then used in https://github.com/openshift/cluster-monitoring-operator/pull/1910 to make these data available in Superset DataHat or Tableau.
See also PR https://github.com/openshift/console/pull/12527 for detailed information about the collected metrics.
=> OCPBUGS-12439: Add new PrometheusRule to collect metrics for cluster-monitoring-operator

pkg/console/operator/sync_v400.go, pkg/console/subresource/util/util.go, pkg/console/subresource/util/util_test.go
When trying to enable single plugin in the console operator's config multiple times the redeployed console will crash.
This PR makes list of plugins unique.
=> OCPBUGS-5059: Make enabled plugins unique

pkg/api/api.go, pkg/console/controllers/clidownloads/controller.go, pkg/console/starter/starter.go
When the custom downloads route is set we should be updating the ConsoleCLIDownloads link as well.
=> OCPBUGS-12990: Update command line tools URL with custom downloads route

pkg/console/controllers/route/controller.go, pkg/console/starter/starter.go
Backport of:
- https://github.com/openshift/console-operator/pull/735
=> [release-4.11] OCPBUGS-11343: Distinguish between route conditions and remove the old ones

manifests/0000_90_console-operator_02_servicemonitor.yaml, manifests/0000_90_console_02_servicemonitor.yaml
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md
=> CONSOLE-3278: Add client certificate and key to service monitor

pkg/console/controllers/route/controller.go, pkg/console/starter/starter.go
Backport of:
- https://github.com/openshift/console-operator/pull/745
=> [release-4.10] OCPBUGS-14845: Distinguish between route conditions and remove the old ones

manifests/03-rbac-role-cluster-extensions.yaml
**Fixes:**
Epic: [ODC-7241: Include Serverless Function Samples in our Sample Catalog](https://issues.redhat.com/browse/ODC-7241) 
Story: [ODC-7333: Update console-operator to latest API to provide the ConsoleSample CRD, add RBAC permissions](https://issues.redhat.com/browse/ODC-7333)
**Related issues:**
* https://github.com/openshift/enhancements/pull/1429
* Rendered preview: https://github.com/jerolimov/openshift-enhancements/blob/console-samples/enhancements/console/samples.md
* https://github.com/openshift/api/pull/1503
**Changes**
Just add `consolesamples` as new resource type to the `ClusterRole` "console-extensions-reader".
**CRD**
To automatically add the CRD it's also required to update the `openshift/api` dependency to the latest version. We can do this as soon as …
=> ODC-7333: Add consolesamples to ClusterRole console-extensions-reader to give all users readonly access

manifests/03-rbac-role-cluster.yaml
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-15893
**Analysis / Root cause**: 
While analyzing the bug on a 4.10 cluster, we found two issues:
1. When a user with limited permissions ("a developer"), we could the see a canceled websocket API call to watch HelmChartRepositories
`wss://.../api/kubernetes/apis/helm.openshift.io/v1beta1/helmchartrepositories?watch=true&resourceVersion=70319`
The console (backend) log shows:
```
2023/07/10 12:31:03 Failed to dial backend: 'websocket: bad handshake' Status: '403 Forbidden' URL: 'https://kubernetes.default.svc/apis/helm.openshift.io/v1beta1/helmchartrepositories?watch=true&resourceVersion=44805'
2023/07/10 12:31:19 Failed to dial backend: 'websocket: bad handshake' Status: '403 Forbidden' URL: …
```
=> OCPBUGS-15893: Add missing watch permission for helm-chartrepos-viewers

bindata/routes/console-custom-route.yaml, bindata/routes/console-route.yaml, pkg/console/assets/bindata.go
Add 5 minute haproxy timeout annotation to console route to match most browsers' maximum timeout.
=> CONSOLE-3624: Add haproxy timeout annotation to console routes

manifests/03-rbac-role-cluster.yaml, manifests/03-rbac-role-ns-operator.yaml, pkg/api/api.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/types.go
Backport disable copied CSV fix to 4.12
Blocks https://github.com/openshift/console/pull/13055
=> [release-4.12] OCPBUGS-18563: OLM Pages work when copied CSVs are disabled

Dockerfile.rhel7
Removing the explicit `0000_10_` runlevel will allow these resources to go in with the other console resources in the default runlevel 50 ([docs][1], [implementation][2].  I'm prefixing ConsolePlugin with ~`90_` to sort it towards the back~ `08-a` sort it after [`07-operator.yaml`][3], because [the operator is what serves the `/crdconvert` webhook defined in that CRD][4], but to sort it before `08-clusteroperator.yaml`, to [avoid][5]:
level=error msg=Cluster operator console Available is False with RouteHealth_FailedLoadCA: RouteHealthAvailable: failed to read CA to check route health: configmaps "trusted-ca-bundle" not found
although I'm not entirely clear on why that `trusted-ca-bundle` issue would be related to the positioning of the ConsolePlugin CRD.  Still, even without a clear …
=> OCPBUGS-15834: Dockerfile: Shift ConsolePlugin CRD after the operator Deployment

pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/config_merger_test.go, pkg/console/subresource/deployment/deployment.go
The oauth-serving-cert is now present in all supported OpenShift versions.
The SA CA bundle would've never been a good choice to get the certs from :|
Removes additional unused function that I randomly found.
The original configurable CA logic is kept as it's going to get reused in #800 
=> HOSTEDCP-1250: remove redundant cert check

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go
OLM is an optional component, adding conditional to remove informer on OLM resource
/hold
Need to find more context on the use of OLM resource in console and need to hold for API to be merged in https://github.com/openshift/api/pull/1589
=> OCPVE-719: feat: add support for olm capability

pkg/cmd/crdconversionwebhook/cmd.go
Remove HTTP/2 support for webhook server.
Luckily for us we are exposing a metrics endpoint.
=> OCPBUGS-21972: Disable HTTP/2 for webhook

manifests/03-rbac-role-cluster.yaml, pkg/console/controllers/oauthclients/oauthclients.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go
First PR to prevent oauth-client creation when the oauth.openshift.io API is unavailable.
This splits the controller handling the oauthclients away from the main sync loop.
=> CONSOLE-3804: split oauthclient controller from the common logic

manifests/03-rbac-role-cluster.yaml, pkg/console/controllers/downloadsdeployment/controller.go, pkg/console/controllers/oauthclients/oauthclients.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/starter/starter.go, pkg/console/subresource/route/route.go
Includes two fixes, one to status handling, another is an oversight of a cache write.
/assign @rhamilto 
/cc @csrwng @dgoodwin
=> CONSOLE-3804: Reapply separation of the oauthclients controller

pkg/console/subresource/configmap/brand_ocp.go
/assign @TheRealJon 
We need to get this one in to merge https://github.com/openshift/console-operator/pull/807
=> OCPBUGS-25618: Bump documentationBaseURL to 4.16

bindata/assets/services/console-redirect-service.yaml
The annotation on the console=redirect service conflicts with the one defined on the console service which can cause the service ca controller not to sync the ca certs correctly. Additionally, the console redirect server does not use TLS so the annotation is not needed.
=> OCPBUGS-7656: Remove service ca controller annotation from console-redirect service.

pkg/console/controllers/healthcheck/controller.go
Wrapping functionality of the `CheckRouteHealth` function into a retry so the operator wont be degraded when a route health check starts failing for short period of time.
/assign @TheRealJon 
ccing @wking
=> OCPBUGS-24041: Prevent healthcheck controller from Available=False blipping 

manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml
As the operator loglevel is controlled by the cr operatorLogLevel, and the --v in the deployment has no effect anymore, we should remove the redundant flag
=> NO-JIRA:(chore) remove unused loglevel

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, test/e2e/deployment_replicas_test.go
The node selector for the console deployment requires deploying it on the master nodes, The node selector for the console deployment requires deploying it on the master nodes, while the replica count is determined by the infrastructureTopology, which primarily tracks the workers' setup.
When an OpenShift cluster is installed with a single master node and multiple workers, this leads the console deployment to request 2 replicas as infrastructureTopology is set to HighlyAvailable. Instead, ControlPlaneTopology is set to SingleReplica as expected.
This commit makes the operator drive the number of replicas for the console deployment based on the ControlPlaneTopology rather than the InfrastructureTopology.
=> OCPBUGS-27335: The console-deployment should set the number of replicas based on the ControlPlaneTopology

go.mod, go.sum, pkg/console/controllers/oauthclients/oauthclients.go, pkg/console/status/status.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
/assign @stlaz @jhadvig 
This updates to 4.15 HEAD library-go which contains required fixes and deconflicts the oauthclient changes.
=> [4.15] pick of OCPBUGS-27221: make it impossible double set conditions in a single loop

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go
This is a follow-up on #811/#839 (see [this](https://github.com/openshift/console-operator/pull/811#discussion_r1426816316) comment).
=> CONSOLE-3912: Merge auth cert configmap deployment annotations into one

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, test/e2e/deployment_replicas_test.go
The patch in #838 is not enough for managed clusters with external control planes. In those cases, the console is deployed on the worker nodes, and we should rely on their topology mode. 
This PR also adds some unit tests to cover the external topology mode given the changes in #838 and this PR.
=> OCPBUGS-27335: use InfrastructureTopology for clusters using external CP as the console deploys on the worker nodes

pkg/console/subresource/deployment/deployment.go
This fixes
```
E0126 10:06:49.815021       1 base_controller.go:268] ConsoleOperator reconciliation failed: Deployment.apps "console" is invalid: [spec.template.spec.volumes[5].name: Invalid value: "ca-bundle.crt": must not contain dots, spec.template.spec.containers[0].volumeMounts[5].name: Not found: "ca-bundle.crt"]
```
when custom CA config map is set for the OIDC provider.
/cc @liouk 
/cc @yanpzhan
=> CONSOLE-3912: OIDC: setup the volume name properly when custom CA is configured

bindata/assets/deployments/console-deployment.yaml
Use startup probe on console container to account for possible long start times from auth initialization. This will help to avoid unnecessary restarts of the console pod.
=> OCPBUGS-29479: Add startupProbe to console container.

pkg/console/subresource/deployment/deployment.go, pkg/console/subresource/deployment/deployment_test.go, test/e2e/deployment_replicas_test.go
Manual backport of https://github.com/openshift/console-operator/pull/841
=> OCPBUGS-31619: use InfrastructureTopology for clusters using external CP as the console deploys on the worker nodes

pkg/console/controllers/upgradenotification/controller.go
- Check the `currentVersion` and `desiredVersion` variable before triggering the notification.
=> OCPBUGS-20129: Fix triggering `upgradenotification` in the cluster installation time

pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/service/controller.go, pkg/console/controllers/upgradenotification/controller.go, pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/operator/sync_v400_test.go, pkg/console/starter/starter.go
Reverts #895 ; tracked by [TRT-1664](https://issues.redhat.com//browse/TRT-1664)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Suspected of causing console operator pod panics
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-aws-sdn-serial
```
CC: @jhadvig
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic< …
=> TRT-1664: Revert #895 "CONSOLE-4047: Console-operator should be internally using listers for fetching data"

Dockerfile.rhel7
Allow this ARG to be overriden by builds so that OKD builds may have the correct branding by default without requiring an additional configmap.
OKD/SCOS builds pass the build-arg `TAGS=scos`, so `pkg/console/subresource/configmap/brand_okd.go` which has `//go:build !ocp` will be built instead of `pkg/console/subresource/configmap/brand_ocp.go` which has `//go:build ocp`.
This change should not affect the OCP build of the console-operator image.
This change will allow OKD to drop the branding image from the payload: https://github.com/openshift/origin-branding/
=> OKD-214: Dockerfile: Add ARG TAGS=ocp

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
Fetching ORGANIZATION_ID is too noisy on the OCM side. Lets rather cache it on main operator controller instance and use when building the console-config CM. 
The correct order for setting the ID should be:
1. custom ORGANIZATION_ID is awailable as telemetry annotation on console-operator config or in telemetry-config configmap
2. cached ORGANIZATION_ID is available on the operator controller instance
**else** fetch the ORGANIZATION_ID from OCM
=> OCPBUGS-33715: Cache organization ID

pkg/cmd/crdconversionwebhook/converter/framework.go
This change updates the message verbs to use %q instead of %s, where appropriate, to properly escape output.
=> OCPBUGS-31777: Updates message verbs to use %q where appropriate.

README.md, bindata/assets/services/console-nodeport-service.yaml, bindata/assets/services/downloads-nodeport-service.yaml, docs/alb-ingress-rosa-hcp.md, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/healthcheck/controller.go, pkg/console/controllers/oauthclients/oauthclients.go, pkg/console/controllers/route/controller.go, pkg/console/controllers/service/controller.go, pkg/console/controllers/util/util.go, pkg/console/controllers/util/util_test.go, pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go
Part of the implementation of [Make Ingress optional for HyperShift EP](https://github.com/openshift/enhancements/pull/1415). Note that this change targets only HyperShift managed deployments and should not impact standalone OpenShift installations.
This PR:
- Implements [alternative ingress fields](https://github.com/openshift/api/pull/1887) from the console operator config API
- Skips component route customizations if ingress capability is disabled
- Uses NodePort type for console and downloads services if ingress capability is disabled
- Adds document to describe how to implement alternative ingress on ROSA
=> OCPBUGS-33787: Tolerate the absence of ingress capability on HyperShift clusters

docs/alb-ingress-rosa-hcp.md, manifests/06-trusted-ca-configmap.yaml, manifests/07-operator-ibm-cloud-managed.yaml, manifests/07-operator.yaml
The alternative ingress can be provided via the console config API. This PR ensures that health checks to the alternative ingress pass TLS certificate validation even when the TLS certificate has an unknown CA.
Additionally, this PR would help with the proxy support [similar to how it was done in the cluster ingress operator](https://github.com/openshift/cluster-ingress-operator/pull/334).
=> OCPBUGS-33787: Add cluster wide trusted CA bundle to operator

manifests/07-operator.yaml, quickstarts/consolequickstart-install-cryostat.yaml, quickstarts/impersonate-user.yaml, quickstarts/install-helmchartrepo-ns.yaml, quickstarts/install-serverless.yaml, quickstarts/jboss-eap7-with-helm.yaml, quickstarts/manage-helm-repos.yaml, quickstarts/node-with-s2i.yaml, quickstarts/quarkus-with-helm.yaml, quickstarts/quarkus-with-s2i.yaml, quickstarts/spring-with-s2i.yaml
Reverts #914 ; tracked by [TRT-1733](https://issues.redhat.com//browse/TRT-1733)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Hypershift is permafailing on 4.17, the manifests have a master node selector which will never schedule on a hosted hypershift cluster
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job 
periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance should pass …
```
=> TRT-1733: Revert #914 "OCPBUGS-29547: Apply hypershift cluster-profile for ibm-cloud-managed"

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
Manual backport of https://github.com/openshift/console-operator/pull/905 since [additional commit](https://github.com/openshift/console-operator/pull/913) needed to be cherry-picked.
=>  [release-4.16] OCPBUGS-34012: Cache organization ID

pkg/console/telemetry/telemetry.go
Tested the change locally and can confirm we are getting the external ID now.
=> OCPBUGS-38549: Get externalOrganizationID instead of the organizationID

pkg/console/status/auth_status.go
Due to [this change](https://github.com/openshift/console-operator/pull/907/files#diff-8c5a69d560f0051604d71443b7331e22477075face20b6ea723b0fc71e1437b0L153-R163), the condition's `Message` field has now a zero value of `nil` (due to using the `ConditionApplyConfiguration`), while before it was simply `""`, which is a valid value for `Message`.
This PR simply initializes the `Message` field to an empty string.
=> OCPBUGS-44556: console/status: set initial value of Message field

pkg/console/controllers/clioidcclientstatus/controller.go, pkg/console/controllers/oidcsetup/oidcsetup.go, pkg/console/status/auth_status.go
Fixes [OCPBUGS-44953](https://issues.redhat.com/browse/OCPBUGS-44953) by resetting the AuthStatusHandler.currentClientID to an empty string when the Authentication.Spec.Type is not set to OIDC.
Additionally, protects against a degraded state when AuthStatusHandler.currentClientID is set but there is no evidence of OIDC providers being configured in the spec by only adding current clients in the Authentication status when both the currentClientID is set and there is evidence of OIDC providers being configured. 
Adds a warning log when we notice the currentClientID is set but there is no evidence of OIDC providers being configured.
=> OCPBUGS-44953: don't set current clients when no OIDC providers are configured

manifests/01-operator-config.yaml, pkg/console/subresource/configmap/configmap_test.go, pkg/console/subresource/consoleserver/config_builder.go, pkg/console/subresource/consoleserver/config_builder_test.go, pkg/console/subresource/consoleserver/config_merger_test.go, pkg/console/subresource/consoleserver/types.go
Jira: https://issues.redhat.com/browse/ODC-7721
This pull request introduces changes to manage the visibility of different perspectives in the console server configuration. The changes include adding a new type for perspective IDs, updating the configuration builder to handle perspective visibility, and modifying the operator configuration manifest.
Changes to perspective management:
* [`pkg/console/subresource/consoleserver/types.go`](diffhunk://#diff-800af91abd4a802bcb0ff987850f14f9c4c8b7dd2ffdbb9ca601080deab21471R205-R214): Added `PerspectiveID` type and constants for admin and developer perspectives.
Configuration updates:
* [`pkg/console/subresource/consoleserver/config_builder.go`](diffhunk://#diff-4c176497477ce0b7c52110bc62b4d7cbe480530f729b644af85f38c053eb753eR503-R512): Modified …
=> ODC-7721: Disable developer perspective by default

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
=> OCPBUGS-45514: Report email_domain to telemetry

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
Reverts #950 ; tracked by OCPBUGS-51156
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Multiple payload failures due to console-operator panic
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn-conformance 10
```
CC: @jhadvig
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:< …
=> OCPBUGS-51156: Revert #950 "OCPBUGS-45514: Report email_domain to telemetry"

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
The original PR needed to be [reverted](https://github.com/openshift/console-operator/pull/961) due to panicking operator.
=> OCPBUGS-45514: Report email_domain to telemetry + fix panic for uninitialized mail value.

pkg/console/operator/operator.go, pkg/console/operator/sync_v400.go, pkg/console/telemetry/telemetry.go
Reverts openshift/console-operator#962 
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Multiple payload failures due to console-operator panic
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn-conformance 10
```
CC: @jhadvig
=> OCPBUGS-51379: Re-revert Report email_domain to telemetry + fix panic for uninitialized mail value.

manifests/03-rbac-role-cluster.yaml, pkg/api/api.go, pkg/console/controllers/route/controller.go, pkg/console/starter/starter.go, pkg/console/subresource/route/route.go, pkg/console/subresource/route/route_test.go
Due to this change Routes controller needs to start fetching IngressController `default` instance form the `openshift-ingress-operator` namespace and check if the `Sepc.DefaultCertificate` is set. If so, console-operator does not need to enforce setting the custom TLS secret for custom route, in the `ValidateCustomRouteConfig` method.
+ Add unit tests for the NewRouteConfig function, for which I needed to make the `RouteControllerSpec` fields public.
=> OCPBUGS-51256: Custom route TLS should be optional when IngressController's DefaultCertificate is set 

.gitignore, vendor/golang.org/x/sys/unix/dev_aix_ppc.go, vendor/golang.org/x/sys/unix/dev_aix_ppc64.go, vendor/golang.org/x/sys/unix/dev_zos.go
Image build was failing on Konflux due to missing go mod dependencies.
```
2025-04-04 17:29:46,063 ERROR vendor directory changed after vendoring:
A	vendor/golang.org/x/sys/unix/dev_aix_ppc.go
A	vendor/golang.org/x/sys/unix/dev_aix_ppc64.go
A	vendor/golang.org/x/sys/unix/dev_zos.go
2025-04-04 17:29:50,718 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
```
Konflux ignores .gitignore files since its a possible security gap.
=> ART-12521: update go mod dependency for konflux

Makefile, test-e2e.sh, test-unit.sh
In order for prow to contribute tests output to sippy our unit and e2e tests need to generate junit files.
For that reason I've rewrote how the unit tests and e2e tests are being executed. 
/assign @TheRealJon @yapei
=> CONSOLE-4481: Add junit generation for unit and e2e testing

bindata/assets/deployments/downloads-deployment.yaml, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go, test/e2e/downloads_test.go
Updating the downloads server in order for it to serve the rhel8 and rhel9 binaries for the Linux OS.
Also needed to update `CLIDownloadsSyncController` controller that is responsible for creating the ConsoleCLIDownloads CR of `oc` binaries.
Screen:
Originally I wanted to put all the oc + oc.rhel8 + oc.rhel9 into a single archive, but that would be a huge one, more then 500MB 🤯  so I rather added an archive for each binary type.
/assign @Mylanos 
@opayne1 Im open for discussion about the name for the link, cause basically what I did is I've only appended ` - RHEL 8` or ` - RHEL 9` for RHEL binaries (`oc.rhel8` and `oc.rhel9`)
=> CONSOLE-4523: Add rhel8 and rhel9 oc binaries for Linux OS in CLI downloads

bindata/assets/deployments/downloads-deployment.yaml, pkg/console/controllers/clidownloads/controller.go, pkg/console/controllers/clidownloads/controller_test.go, test/e2e/downloads_test.go
Reverts openshift/console-operator#976
The original PR is causing failures during minor version upgrades.
/assign @dgoodwin 
/cc @jhadvig
=> OCPBUGS-55082: Revert "Add rhel8 and rhel9 oc binaries for Linux OS in CLI downloads"

quickstarts/add-healthchecks-quickstart.yaml, quickstarts/install-helmchartrepo-ns.yaml, quickstarts/jboss-eap7-with-helm.yaml, quickstarts/manage-helm-repos.yaml, quickstarts/monitor-sampleapp-quickstart.yaml, quickstarts/node-with-s2i.yaml, quickstarts/quarkus-with-helm.yaml, quickstarts/quarkus-with-s2i.yaml, quickstarts/rhdh-installation-via-helm.yaml, quickstarts/rhdh-installation-via-operator.yaml, quickstarts/sample-application-quickstart.yaml, quickstarts/spring-with-s2i.yaml
Update the following quick starts to make it work in the converged perspective
1. Add health checks to your sample application
2. Add Helm Chart Repositories to extend the Developer Catalog for your project
3. Get started with JBoss EAP 7 using a Helm Chart
4. Manage available content in the Helm Chart Catalog
5. Monitor your sample application
6. Get started with Node
7. Get started with Quarkus using a Helm Chart
8. Get started with Quarkus using s2i
9. Install Red Hat Developer Hub (RHDH) using Helm Chart
10. Install Red Hat Developer Hub (RHDH) using the Operator
11. Get started with Spring
=> ODC-7780: update quick starts to work in the converged perspective

manifests/0000_90_console-operator_03_console_plugin_storage_migration.yaml, manifests/07-operator-ibm-cloud-managed.yaml, profile-patches/ibm-cloud-managed/07-operator.yaml-patch
/assign @wking 
@linoyaslan FYI
=> OCPBUGS-57129: Add missing Console capability annotation

quickstarts/rhdh-installation-via-operator.yaml
This PR fixes the references to a deprecated `Backstage` API Version in the `Install Red Hat Developer Hub (RHDH) using the Operator` Quickstart.
ref: https://issues.redhat.com/browse/RHDHBUGS-247
/cc @christoph-jerolimov @logonoff
=> OCPBUGS-58320: Fix deprecated API Version in RHDH Operator Quickstart

pkg/console/operator/sync_v400.go, pkg/console/subresource/configmap/configmap.go, pkg/console/subresource/configmap/configmap_test.go
For OIDC Authentication, the IdP provider TrustedAuthority CM should first be read from the `openshift-config` namespace and synced to the `openshfit-console` namespace. 
This PR:
* Ensures using the correct lister to pull the CM from the target namespace (i.e `openshift-console`)
* Adds a progress condition for tracking any errors getting the CM similar to other resource conditions
=> OCPBUGS-45300: Wire synced OIDC Auth CM to Console
